//CATEGORIAS: 
//Classic Literature & Fiction
//Comics & Graphic Novels
//Science
//Childish
//Business & Money
//Biography
//Cooking

const seedBooks = [
  {
    title: "Martín Fierro",
    author: "José Hernández",
    img: "https://www.alianzaeditorial.es/imagenes/libros/grande/9788420656403-martin-fierro.jpg",
    rating: 4.8,
    category: "Classic Literature & Fiction",
    price: 10,
    stock: 12,
    publisher: "John Doe Editions",
    maturityRating: "Recommended for all audiences",
    description:
      "The story about the rebel Gaucho, one of the most famous pieces of argentine literature",
  },
  {
    title: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling",
    img: "http://books.google.com/books/content?id=1o7D0m_osFEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    rating: 4.9,
    category: "Classic Literature & Fiction",
    price: 15.5,
    stock: 18,
    publisher: "Rowman & Littlefield",
    maturityRating: "Recommended for all audiences",
    description:
      "There is a plot, Harry Potter. A plot to make most terrible things happen at Hogwarts School of Witchcraft and Wizardry this year.' Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as though turned to stone... Dobby's sinister predictions seem to be coming true. Having now become classics of our time, the Harry Potter ebooks never fail to bring comfort and escapism to readers of all ages. With its message of hope, belonging and the enduring power of truth and love, the story of the Boy Who Lived continues to delight generations of new readers.",
  },
  {
    title: "The Sandman Vol. 1: Preludes & Nocturnes",
    author: "Neil Gaiman",
    img: "http://books.google.com/books/content?id=AfW0AAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
    rating: 4.8,
    category: "Comics & Graphic Novels",
    price: 15.99,
    stock: 8,
    publisher: "DC",
    maturityRating: "Recommended for all audiences",
    description:
      'NEW YORK TIMES bestselling author Neil Gaiman\'s transcendent series SANDMAN is often hailed as the definitive Vertigo title and one of the finest achievements in graphic storytelling. Gaiman created an unforgettable tale of the forces that exist beyond life and death by weaving ancient mythology, folklore and fairy tales with his own distinct narrative vision. In PRELUDES & NOCTURNES, an occultist attempting to capture Death to bargain for eternal life traps her younger brother Dream instead. After his seventy-year imprisonment and eventual escape, Dream, also known as Morpheus, goes on a quest for his lost objects of power. On his arduous journey Morpheus encounters Lucifer, John Constantine, and an all-powerful madman. This book also includes the story "The Sound of Her Wings," which introduces us to the pragmatic and perky goth girl Death. Collecting issues #1-8, this new edition of PRELUDES & NOCTURNES features the improved production values and coloring from the Absolute Edition.',
  },
  {
    title: "Moby Dick",
    author: "Herman Melville",
    img: "http://books.google.com/books/content?id=GL7BrQEACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE70PONzfYnKNannawhaPS3tnMEj1M50hZUCTbSEzH4cHXBWojNfIcp5mpN77vxYMYsQXUnwrkOO5I4Y-n6ZirXCompIHNR9KFkai5gXgRa6SFgzzpOa0yZJDE-tVtcvSatusvJ0i&source=gbs_api",
    rating: 4.8,
    category: "Classic Literature & Fiction",
    price: 8,
    stock: 5,
    publisher: "CreateSpace Independent Publishing Platform",
    maturityRating: "Recommended for all audiences",
    description:
      'Moby-Dick; or, The Whale is a novel by Herman Melville, in which Ishmael narrates the monomaniacal quest of Ahab, captain of the whaler Pequod, for revenge on the albino sperm whale Moby Dick, which on a previous voyage destroyed Ahab\'s ship and severed his leg at the knee. Although the novel was a commercial failure and out of print at the time of the author\'s death in 1891, its reputation grew immensely during the twentieth century. D. H. Lawrence called it "one of the strangest and most wonderful books in the world," and "the greatest book of the sea ever written." Moby-Dick is considered a Great American Novel and an outstanding work of the Romantic period in America and the American Renaissance. "Call me Ishmael" is one of world literature\'s most famous opening sentences. The product of a year and a half of writing, the book is dedicated to Nathaniel Hawthorne, "in token of my admiration for his genius," and draws on Melville\'s experience at sea, on his reading in whaling literature, and on literary inspirations such as Shakespeare and the Bible. The detailed and realistic descriptions of whale hunting and of extracting whale oil, as well as life aboard ship among a culturally diverse crew, are mixed with exploration of class and social status, good and evil, and the existence of God. In addition to narrative prose, Melville uses styles and literary devices ranging from songs, poetry and catalogs to Shakespearean stage directions, soliloquies and asides. The author changed the title at the very last moment in September 1851. The work first appeared as The Whale in London in October 1851, and then under its definitive title Moby-Dick in New York in November. The whale, however, appears in both the London and New York editions as "Moby Dick," with no hyphen. The British edition of five hundred copies was not reprinted during the author\'s life, the American of almost three thousand was reprinted three times at approximately 250 copies, the last reprinting in 1871. These figures are exaggerated because three hundred copies were destroyed in a fire at Harper\'s; only 3,200 copies were actually sold during the author\'s life.',
  },
  {
    title: "Introduction to Quantum Mechanics",
    author: "David J. Griffiths, Darrell F. Schroeter",
    img: "http://books.google.com/books/publisher/content?id=82FjDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72OSAkI3RKMi3HqIASQZvKY8sbutpXnsCHVmg6gwhs-2a1xlNya5uZhJCIBPxg8pIGUYSBeUHr7xZJzjWFJTrYRN2Z9tjAjbtwrxkfZBWpleqCfjNaDzplwfd0e545bXT-lU9Ri&source=gbs_api",
    rating: 4.6,
    category: "Science",
    price: 8,
    stock: 5,
    publisher: "Cambridge University Press",
    maturityRating: "Recommended for all audiences",
    description:
      "Changes and additions to the new edition of this classic textbook include a new chapter on symmetries, new problems and examples, improved explanations, more numerical problems to be worked on a computer, new applications to solid state physics, and consolidated treatment of time-dependent potentials.",
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    img: "http://books.google.com/books/content?id=yl4dILkcqm4C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
    rating: 4.5,
    category: "Classic Literature & Fiction",
    price: 9,
    stock: 20,
    publisher: "Open Court",
    maturityRating: "NOT_MATURE",
    description:
      "A PBS Great American Read Top 100 Pick One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell by chance into the hands of the hobbit Bilbo Baggins. From Sauron's fastness in the Dark Tower of Mordor, his power spread far and wide. Sauron gathered all the Great Rings to him, but always he searched for the One Ring that would complete his dominion. When Bilbo reached his eleventy-first birthday he disappeared, bequeathing to his young cousin Frodo the Ruling Ring and a perilous quest: to journey across Middle-earth, deep into the shadow of the Dark Lord, and destroy the Ring by casting it into the Cracks of Doom. The Lord of the Rings tells of the great quest undertaken by Frodo and the Fellowship of the Ring: Gandalf the Wizard; the hobbits Merry, Pippin, and Sam; Gimli the Dwarf; Legolas the Elf; Boromir of Gondor; and a tall, mysterious stranger called Strider. This new edition includes the fiftieth-anniversary fully corrected text setting and, for the first time, an extensive new index. J.R.R. Tolkien (1892-1973), beloved throughout the world as the creator of The Hobbit, The Lord of the Rings, and The Silmarillion, was a professor of Anglo-Saxon at Oxford, a fellow of Pembroke College, and a fellow of Merton College until his retirement in 1959. His chief interest was the linguistic aspects of the early English written tradition, but while he studied classic works of the past, he was creating a set of his own.",
  },
  {
    title:
      "Studies in J. D. Salinger: Reviews, Essays, and Critiques of The Catcher in the Rye, and Other Fiction",
    author: "Marvin Laser, Norman Fruman",
    img: "http://books.google.com/books/content?id=yEhbAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    rating: 5,
    category: "Fiction",
    price: 12,
    stock: 16,
    publisher: "Public",
    maturityRating: "NOT_MATURE",
    description:
      "Collects essays that look at J.D. Salinger's The Catcher in the Rye through a philosophical approach.",
  },
  {
    title: "Rayuela",
    author: "Julio Cortázar",
    img: "https://www.actualidadliteratura.com/wp-content/uploads/2017/02/An%C3%A1lisis-de-Rayuela-de-Julio-Cort%C3%A1zar.jpg",
    rating: 4,
    category: "Classic Literature & Fiction",
    price: 14,
    stock: 22,
    publisher: "Catedra Ediciones",
    maturityRating: "NOT_MATURE",
    description:
      "Por primera vez se edita «Rayuela» como un clásico de la novela contemporánea. Todo el conjunto de materiales que aporta esta edición (introducción, abundantes notas, plano, fotografías) servirán al lector para comprender mejor y disfrutar más con esta gran novela. Al aclararse tantas alusiones y técnicas narrativas, resplandece con más claridad el sentido profundo del relato: la búsqueda constante, el humor, el juego, la nostalgia de una verdadera vida, el paso soñado «de la tierra al cielo»...",
  },
  {
    title: "Mixing Secrets for the Small Studio",
    author: "Mike Senior",
    img: "https://images-na.ssl-images-amazon.com/images/I/41vyO5oQXAL._SX404_BO1,204,203,200_.jpg",
    rating: 4.7,
    category: "Science",
    price: 20,
    stock: 10,
    publisher: "Routledge",
    maturityRating: "Recommended for all audiences",
    description:
      "Mixing Secrets for the Small Studio is the best-selling primer for small-studio enthusiasts who want chart-ready sonics in a hurry. Drawing on the back-room strategies of more than 160 famous names, this entertaining and down-to-earth guide leads you step-by-step through the entire mixing process. On the way, you'll unravel the mysteries of every type of mix processing, from simple EQ and compression through to advanced spectral dynamics and fairy dust effects. User-friendly explanations introduce technical concepts on a strictly need-to-know basis, while chapter summaries and assignments are perfect for school and college use.",
  },
  {
    title: "El tesoro del pirata",
    author: "Núria Cussó Grau",
    img: "https://images-na.ssl-images-amazon.com/images/I/51L8b1qtrTL._SX403_BO1,204,203,200_.jpg",
    rating: 4.5,
    category: "Childish",
    price: 20,
    stock: 10,
    publisher: "Editorial el Pirata",
    maturityRating: "Recommended for all audiences",
    description:
      "Pedro es el pirata de seis años más valiente y astuto de los siete mares. A pesar de que aún es muy pequeño, se hace llamar Barbanegra, ¡igual que el pirata más peligroso de la historia!Hoy está triste. ¡No encuentra su tesoro favorito!El tesoro del pirata es el sexto cuento de la colección Aprender a leer en letra MAYÚSCULA e imprenta, con más de 100.000 ejemplares vendidos, que está ordenada en función de la dificultad lectora siendo el número 1 el más sencillo y el número 9 el más complejo. En cada página se encuentra el mismo texto: arriba en letra de imprenta y abajo en letra de PALO (mayúsculas). Permite trabajar la lectura en letra mayúscula y el cambio hacia la letra de imprenta.",
  },
  {
    title: "Just Be Jelly Hardcover",
    author: "Maddie Frost",
    img: "https://images-na.ssl-images-amazon.com/images/I/71p25ldU+FL.jpg",
    rating: 3,
    category: "Childish",
    price: 20,
    stock: 5,
    publisher: "Little, Brown Books for Young Readers",
    maturityRating: "Recommended for all audiences",
    description:
      "A groovy jellyfish helps a scared-of-everything sardine learn to take its problems in stride in this humorous picture book about wiggling your worries away. When a sardine who's scared of everything loses its handbook for staying safe in the sea, it goes into total panic mode. But right as big, scary shadows are surrounding it, the sardine runs into a jellyfish preaching the wisdom of wiggling your worries away. Try it! Wiggle up...wiggle down ...wiggle all around! When you're done, your problems might not seem so enormous—and those scary shadows might turn out to be friends!From the creator of Smug Seagull comes a funny, feel-good story about facing your fears (with the help of a few awesome dance moves)",
  },
  {
    title: "Are You a Cheeseburger?",
    author: "Monica Arnaldo",
    img: "https://images-na.ssl-images-amazon.com/images/I/81mMUmH0YgS.jpg",
    rating: 5,
    category: "Childish",
    price: 13.99,
    stock: 15,
    publisher: "Katherine Tegen Books",
    maturityRating: "Recommended for all audiences",
    description:
      "A Kids' Indie Next List pick! Laugh-out-loud humor and a tender friendship blossom in author-illustrator Monica Arnaldo’s charming picture book about a lonely raccoon and a glowing seed, and the world’s most important question: Can this seed grow cheeseburgers? Grub is a lonely racoon. Rumbling in the trash. Looking for food. Seed is, well, a seed! Patiently waiting in the trash. Hoping someone will plant it. When the two finally meet, they realize they might be able to help each other! Grub has just one big question first: What will Seed grow? Could Seed grow Grub’s favorite food, mouthwatering cheeseburgers? Seed isn’t sure what a cheeseburger is exactly, but . . . maybe! And so begins a hilarious friendship following two unlikely strangers learning more about the other and discovering the pressure that comes with fulfilling expectations. Author-illustrator Monica Arnaldo will leave readers giggling and clamoring for more in this charming story that celebrates the unexpected—and how the most special friendships bloom only when we are unapologetically ourselves.",
  },
  {
    title: "Time for School, Little Blue Truck",
    author: "Alice Schertle",
    img: "https://images-na.ssl-images-amazon.com/images/I/A1ee9JJRUCS.jpg",
    rating: 4.8,
    category: "Childish",
    price: 10.77,
    stock: 35,
    publisher: "HMH Books for Young Readers",
    maturityRating: "Recommended for all audiences",
    description:
      "Ride along to school with the #1 New York Times best-selling Little Blue Truck and meet Blue's new friend: a bright yellow school bus. Beep-beep! Little Blue Truck and his good friend Toad are excited to meet a bright yellow school bus on the road. They see all the little animals lined up in the school bus’s many windows, and Blue wishes he could be a school bus too. What a fun job—but much too big for a little pickup like Blue. Or is it? When somebody misses the bus, it’s up to Blue to get his friend to school on time. Beep! Beep! Vroom! Also enjoy Blue’s bedtime ride in Good Night, Little Blue Truck and his trip to the city in Little Blue Truck Leads the Way.",
  },
  {
    title: "Great Circle: A novel",
    author: "Conrad Aiken",
    img: "https://m.media-amazon.com/images/I/51VzvMROz9L.jpg",
    rating: 5,
    category: "Classic Literature & Fiction",
    price: 25,
    stock: 17,
    publisher: "Open Road Media",
    maturityRating: "Recommended for all audiences",
    description:
      "The train races from New York to Boston. For Andrew Cather, it is much too fast. He will return home three days early, and he is both terrified and intrigued by what he may find there. He pictures himself unlocking the door to his quiet Cambridge house, padding silently through its darkened halls, and finally discovering the thing he both fears and yearns to see: his wife in the arms of another man. Cather knows that what he finds in Cambridge may destroy his life, yet finally set him free. A masterful portrait of an average man at the edge of a shocking precipice, Great Circle is a triumph of psychological realism. One of Sigmund Freud’s favorite novels, it is a probing exploration of the secrets of consciousness.",
  },
  {
    title: "Mi Gran Libro de experimentos",
    author: "Mar Benegas",
    img: "https://images-na.ssl-images-amazon.com/images/I/81YOoodAneL.jpg",
    rating: 4.6,
    category: "Childish",
    price: 18,
    stock: 18,
    publisher: "Susaeta",
    maturityRating: "ALL",
    description:
      "Convierte un huevo en una pelota o unos fideos en verdaderos bailarines, fabrica tu propia nave espacial o tu bosque mágico de cristales, consigue que llueva o que la arena no se moje, manda mensajes en tinta invisible que solo otro científico como tú logre leer en secreto... ¡No es magia, es ciencia! ¡Atrévete a convertirte en un pequeño gran científico!",
  },
  {
    title: "Harry Potter Coloring Book",
    author: "Scholastic",
    img: "https://images-na.ssl-images-amazon.com/images/I/81uHJU1iy9L.jpg",
    rating: 4.8,
    category: "Childish",
    price: 20,
    stock: 25,
    publisher: "Scholastic Inc.",
    maturityRating: "8 years and up",
    description: "Unleash your creativity and escape to one of the most beloved series of all time. From the heraldry of the four Hogwarts houses to the extravagant wares of Weasleys Wizard Wheezes, the world of Harry Potter overflows with radiant color. Filled with intricate illustrations and elaborate designs used in the making of the Harry Potter films, this book invites you to imbue the wizarding world with color in your own explorations of Hogwarts Castle, the Forbidden Forest, and much more. You will also find pages of magical creatures and iconic scenes from the films, from the Sorting Ceremony in Harrys first year, to the unforgettable final battle between Harry and Lord Voldemort, as well as some of the marvelous props used in the movies, such as The Quibbler, Quidditch World Cup posters, and the Triwizard Cup. Also includes sixteen pages of full-color art from the movies to inspire you as you draw.",
  },
  {
    title: "Fallout: The Vault Dweller's Official Cookbook",
    author: "Victoria Rosenthal",
    img: "https://images-na.ssl-images-amazon.com/images/I/8133p-u2BaL.jpg",
    rating: 4.8,
    category: "Cooking",
    price: 32,
    stock: 23,
    publisher: "Insight Editions",
    maturityRating: "ALL",
    description: "Craft your own glass of Nuka-Cola, a bowl of BlamCo Mac & Cheese, and more with the recipes in Fallout: The Official Cookbook. Based on the irradiated delicacies of the world of Bethesda Entertainment’s Fallout, this Vault-Tec–approved cookbook provides fans of the award-winning series with recipes inspired by their favorite Fallout foods. Whip up tasty versions of the Mirelurk egg omelette, throw some deathclaw meat on the grill, and re-create BlamCo Mac & Cheese with Fallout: The Official Cookbook.",
  },
  {
    title: "Swann's Way: In Search of Lost Time, Volume One",
    author: "Marcel Proust",
    img: "https://images-na.ssl-images-amazon.com/images/I/51b6H4g2dcL.jpg",
    rating: 4.4,
    category: "Classic Literature & Fiction",
    price: 12,
    stock: 6,
    publisher: "Independently published",
    maturityRating: "MATURE",
    description: "A new, beautifully laid-out edition of Marcel Proust's 1922 classic novel, the first volume of his In Search of Lost Time series (also known as, The Remembrance of Things Past). This edition is based on the 1922 translation by C.K. Scott Moncrieff (1889-1930).",
  },
  {
    title: "The Invisible Life of Addie LaRue",
    author: "V. E. Schwab",
    img: "https://images-na.ssl-images-amazon.com/images/I/91Ql48Y0mqL.jpg",
    rating: 4.5,
    category: "ALL",
    price: 11,
    stock: 8,
    publisher: "Tor Books: Illustrated edition",
    maturityRating: "MATURE",
    description: "France, 1714: in a moment of desperation, a young woman makes a Faustian bargain to live forever―and is cursed to be forgotten by everyone she meets. Thus begins the extraordinary life of Addie LaRue, and a dazzling adventure that will play out across centuries and continents, across history and art, as a young woman learns how far she will go to leave her mark on the world. But everything changes when, after nearly 300 years, Addie stumbles across a young man in a hidden bookstore and he remembers her name.",
  },
  {
    title: "The Midnight Library: A Novel",
    author: "Matt Haig",
    img: "https://images-na.ssl-images-amazon.com/images/I/81YzHKeWq7L.jpg",
    rating: 4.4,
    category: "Science Fiction & Fantasy",
    price: 14,
    stock: 24,
    publisher: "Viking",
    maturityRating: "MATURE",
    description: "Somewhere out beyond the edge of the universe there is a library that contains an infinite number of books, each one the story of another reality. One tells the story of your life as it is, along with another book for the other life you could have lived if you had made a different choice at any point in your life. While we all wonder how our lives might have been, what if you had the chance to go to the library and see for yourself? Would any of these other lives truly be better? In The Midnight Library, Matt Haig's enchanting blockbuster novel, Nora Seed finds herself faced with this decision. Faced with the possibility of changing her life for a new one, following a different career, undoing old breakups, realizing her dreams of becoming a glaciologist; she must search within herself as she travels through the Midnight Library to decide what is truly fulfilling in life, and what makes it worth living in the first place.",
  },
  {
    title: "The Alchemist, 25th Anniversary",
    author: "Paulo Coelho",
    img: "https://images-na.ssl-images-amazon.com/images/I/51kcX5PpaZL.jpg",
    rating: 4.7,
    category: "Science Fiction & Fantasy",
    price: 13,
    stock: 4,
    publisher: "HarperOne",
    maturityRating: "ALL",
    description: "A special 25th anniversary edition of the extraordinary international bestseller, including a new Foreword by Paulo Coelho. Combining magic, mysticism, wisdom and wonder into an inspiring tale of self-discovery,The Alchemist has become a modern classic, selling millions of copies around the world and transforming the lives of countless readers across generations. Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined. Santiago's journey teaches us about the essential wisdom of listening to our hearts, of recognizing opportunity and learning to read the omens strewn along life's path, and, most importantly, to follow our dreams.",
  },
  {
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    img: "https://images-na.ssl-images-amazon.com/images/I/71OFqSRFDgL.jpg",
    rating: 4.6,
    category: "Science Fiction & Fantasy",
    price: 10,
    stock: 12,
    publisher: "Simon & Schuster",
    maturityRating: "MATURE",
    description: "Guy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television “family.” But when he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didn’t live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television, Montag begins to question everything he has ever known.",
  },
  {
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    img: "https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg",
    rating: 4.7,
    category: "Business & Money",
    price: 8,
    stock: 12,
    publisher: "Plata Publishing",
    maturityRating: "MATURE",
    description: "Business & Money",
  },
  {
    title: "The Intelligent Investor: The Definitive Book on Value Investing.",
    author: "Benjamin Graham",
    img: "https://images-na.ssl-images-amazon.com/images/I/91yj3mbz4JL.jpg",
    rating: 4.7,
    category: "Business & Money",
    price: 15,
    stock: 16,
    publisher: "Harper Business",
    maturityRating: "Recommended for all audiences",
    description: `This classic text is annotated to update Graham's timeless wisdom for today's market conditions... The greatest investment advisor of the twentieth century, Benjamin Graham, taught and inspired people worldwide. Graham's philosophy of "value investing" -- which shields investors from substantial error and teaches them to develop long-term strategies -- has made The Intelligent Investor the stock market bible ever since its original publication in 1949. Over the years, market developments have proven the wisdom of Graham's strategies. While preserving the integrity of Graham's original text, this revised edition includes updated commentary by noted financial journalist Jason Zweig, whose perspective incorporates the realities of today's market, draws parallels between Graham's examples and today's financial headlines, and gives readers a more thorough understanding of how to apply Graham's principles.`,
  },
  {
    title: "Noise: A Flaw in Human Judgment",
    author: "Daniel Kahneman",
    img: "https://images-na.ssl-images-amazon.com/images/I/81G92Rdj7FS.jpg",
    rating: 4.4,
    category: "Business & Money",
    price: 19,
    stock: 7,
    publisher: "Little, Brown Spark",
    maturityRating: "MATURE",
    description: `From the Nobel Prize-winning author of Thinking, Fast and Slow and the coauthor of Nudge, a revolutionary exploration of why people make bad judgments and how to make better ones--"a tour de force” (New York Times). Imagine that two doctors in the same city give different diagnoses to identical patients—or that two judges in the same courthouse give markedly different sentences to people who have committed the same crime. Suppose that different interviewers at the same firm make different decisions about indistinguishable job applicants—or that when a company is handling customer complaints, the resolution depends on who happens to answer the phone. Now imagine that the same doctor, the same judge, the same interviewer, or the same customer service agent makes different decisions depending on whether it is morning or afternoon, or Monday rather than Wednesday. These are examples of noise: variability in judgments that should be identical. In Noise, Daniel Kahneman, Olivier Sibony, and Cass R. Sunstein show the detrimental effects of noise in many fields, including medicine, law, economic forecasting, forensic science, bail, child protection, strategy, performance reviews, and personnel selection. Wherever there is judgment, there is noise. Yet, most of the time, individuals and organizations alike are unaware of it. They neglect noise. With a few simple remedies, people can reduce both noise and bias, and so make far better decisions. Packed with original ideas, and offering the same kinds of research-based insights that made Thinking, Fast and Slow and Nudge groundbreaking New York Times bestsellers, Noise explains how and why humans are so susceptible to noise in judgment—and what we can do about it.`,
  },
  {
    title: "The Premonition: A Pandemic Story",
    author: "Michael Lewis",
    img: "https://images-na.ssl-images-amazon.com/images/I/51y4sn12xoS.jpg",
    rating: 5,
    category: "Business & Money",
    price: 14,
    stock: 8,
    publisher: "W. W. Norton & Company",
    maturityRating: "MATURE",
    description: `For those who could read between the lines, the censored news out of China was terrifying. But the president insisted there was nothing to worry about. Fortunately, we are still a nation of skeptics. Fortunately, there are those among us who study pandemics and are willing to look unflinchingly at worst-case scenarios. Michael Lewis’s taut and brilliant nonfiction thriller pits a band of medical visionaries against the wall of ignorance that was the official response of the Trump administration to the outbreak of COVID-19. The characters you will meet in these pages are as fascinating as they are unexpected. A thirteen-year-old girl’s science project on transmission of an airborne pathogen develops into a very grown-up model of disease control. A local public-health officer uses her worm’s-eye view to see what the CDC misses, and reveals great truths about American society. A secret team of dissenting doctors, nicknamed the Wolverines, has everything necessary to fight the pandemic: brilliant backgrounds, world-class labs, prior experience with the pandemic scares of bird flu and swine flu…everything, that is, except official permission to implement their work. Michael Lewis is not shy about calling these people heroes for their refusal to follow directives that they know to be based on misinformation and bad science. Even the internet, as crucial as it is to their exchange of ideas, poses a risk to them. They never know for sure who else might be listening in.`,
  },
  {
    title: "The Cult of We: WeWork, Adam Neumann, and the Great Startup Delusion",
    author: "Eliot Brown et al.",
    img: "https://m.media-amazon.com/images/I/814jHH+fifL._AC_SX960_SY720_.jpg",
    rating: 4,
    category: "Business & Money",
    price: 20,
    stock: 17,
    publisher: "Crown",
    maturityRating: "MATURE",
    description: `“A juicy investigation into one of Silicon Valley’s most-hyped fallen unicorns.”—Time (Best Books of Summer 2021). The definitive inside story of WeWork, its audacious founder, and what its epic unraveling says about a financial system drunk on the elixir of Silicon Valley innovation—from the Wall Street Journal correspondents (recently featured in the WeWork Hulu documentary) whose scoop-filled reporting hastened the company’s downfall. WeWork would be worth $10 trillion, more than any other company in the world. It wasn’t just an office space provider. It was a tech company—an AI startup, even. Its WeGrow schools and WeLive residences would revolutionize education and housing. One day, mused founder Adam Neumann, a Middle East peace accord would be signed in a WeWork. The company might help colonize Mars. And Neumann would become the world’s first trillionaire. This was the vision of Neumann and his primary cheerleader, SoftBank’s Masayoshi Son. In hindsight, their ambition for the company, whose primary business was subletting desks in slickly designed offices, seems like madness. Why did so many intelligent people—from venture capitalists to Wall Street elite—fall for the hype? And how did WeWork go so wrong? In little more than a decade, Neumann transformed himself from a struggling baby clothes salesman into the charismatic, hard-partying CEO of a company worth $47 billion—on paper. With his long hair and feel-good mantras, the six-foot-five Israeli transplant looked the part of a messianic truth teller. Investors swooned, and billions poured in. Neumann dined with the CEOs of JPMorgan and Goldman Sachs, entertaining a parade of power brokers desperate to get a slice of what he was selling: the country’s most valuable startup, a once-in-a-lifetime opportunity and a generation-defining moment. Soon, however, WeWork was burning through cash faster than Neumann could bring it in. From his private jet, sometimes clouded with marijuana smoke, he scoured the globe for more capital. Then, as WeWork readied a Hail Mary IPO, it all fell apart. Nearly $40 billion of value vaporized in one of corporate America’s most spectacular meltdowns. Peppered with eye-popping, never-before-reported details, The Cult of We is the gripping story of careless and often absurd people—and the financial system they have made.`,
  },
  {
    title: "Will",
    author: "Mark Manson",
    img: "https://images-na.ssl-images-amazon.com/images/I/91t9XuSD6oS.jpg",
    rating: 2,
    category: "Biography",
    price: 20,
    stock: 4,
    publisher: "Penguin Press",
    maturityRating: "MATURE",
    description: `Will Smith’s transformation from a fearful child in a tense West Philadelphia home to one of the biggest rap stars of his era and then one of the biggest movie stars in Hollywood history, with a string of box office successes that will likely never be broken, is an epic tale of inner transformation and outer triumph, and Will tells it astonishingly well. But it's only half the story. Will Smith thought, with good reason, that he had won at life: not only was his own success unparalleled, his whole family was at the pinnacle of the entertainment world. Only they didn't see it that way: they felt more like star performers in his circus, a seven-days-a-week job they hadn't signed up for. It turned out Will Smith's education wasn't nearly over. This memoir is the product of a profound journey of self-knowledge, a reckoning with all that your will can get you and all that it can leave behind. Written with the help of Mark Manson, author of the multi-million-copy bestseller The Subtle Art of Not Giving a F*ck, Will is the story of how one person mastered his own emotions, written in a way that can help everyone else do the same. Few of us will know the pressure of performing on the world's biggest stages for the highest of stakes, but we can all understand that the fuel that works for one stage of our journey might have to be changed if we want to make it all the way home. The combination of genuine wisdom of universal value and a life story that is preposterously entertaining, even astonishing, puts Will the book, like its author, in a category by itself.`,
  },
  {
    title: "Somebody's Daughter: A Memoir",
    author: "Ashley C. Ford",
    img: "https://images-na.ssl-images-amazon.com/images/I/714c3+WWXOS.jpg",
    rating: 4,
    category: "Biography",
    price: 20,
    stock: 6,
    publisher: "Flatiron Books: An Oprah Book",
    maturityRating: "MATURE",
    description: `Through poverty, adolescence, and a fraught relationship with her mother, Ashley C. Ford wishes she could turn to her father for hope and encouragement. There are just a few problems: he’s in prison, and she doesn’t know what he did to end up there. She doesn’t know how to deal with the incessant worries that keep her up at night, or how to handle the changes in her body that draw unwanted attention from men. In her search for unconditional love, Ashley begins dating a boy her mother hates. When the relationship turns sour, he assaults her. Still reeling from the rape, which she keeps secret from her family, Ashley desperately searches for meaning in the chaos. Then, her grandmother reveals the truth about her father’s incarceration . . . and Ashley’s entire world is turned upside down. Somebody’s Daughter steps into the world of growing up a poor Black girl in Indiana with a family fragmented by incarceration, exploring how isolating and complex such a childhood can be. As Ashley battles her body and her environment, she embarks on a powerful journey to find the threads between who she is and what she was born into, and the complicated familial love that often binds them.`,
  },
];

module.exports = seedBooks;
