//CATEGORIAS:
//Classic Literature & Fiction
//Comics & Graphic Novels
//Science
//Kids
//Business & Money
//Biography
//Cooking

const seedBooks = [
    {
      title: "Martín Fierro",
      author: "José Hernández",
      img: "https://www.alianzaeditorial.es/imagenes/libros/grande/9788420656403-martin-fierro.jpg",
      rating: 4.8,
      category: "Classic Literature & Fiction",
      price: 10,
      stock: 12,
      publisher: "John Doe Editions",
      maturityRating: "Recommended for all audiences",
      description:
        "The story about the rebel Gaucho, one of the most famous pieces of argentine literature",
    },
    {
      title: "Harry Potter and the Chamber of Secrets",
      author: "J.K. Rowling",
      img: "http://books.google.com/books/content?id=1o7D0m_osFEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
      rating: 4.9,
      category: "Classic Literature & Fiction",
      price: 15.5,
      stock: 18,
      publisher: "Rowman & Littlefield",
      maturityRating: "Recommended for all audiences",
      description:
        "There is a plot, Harry Potter. A plot to make most terrible things happen at Hogwarts School of Witchcraft and Wizardry this year.' Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as though turned to stone... Dobby's sinister predictions seem to be coming true. Having now become classics of our time, the Harry Potter ebooks never fail to bring comfort and escapism to readers of all ages. With its message of hope, belonging and the enduring power of truth and love, the story of the Boy Who Lived continues to delight generations of new readers.",
    },
    {
      title: "The Sandman Vol. 1: Preludes & Nocturnes",
      author: "Neil Gaiman",
      img: "http://books.google.com/books/content?id=AfW0AAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
      rating: 4.8,
      category: "Comics & Graphic Novels",
      price: 15.99,
      stock: 8,
      publisher: "DC",
      maturityRating: "Recommended for all audiences",
      description:
        'NEW YORK TIMES bestselling author Neil Gaiman\'s transcendent series SANDMAN is often hailed as the definitive Vertigo title and one of the finest achievements in graphic storytelling. Gaiman created an unforgettable tale of the forces that exist beyond life and death by weaving ancient mythology, folklore and fairy tales with his own distinct narrative vision. In PRELUDES & NOCTURNES, an occultist attempting to capture Death to bargain for eternal life traps her younger brother Dream instead. After his seventy-year imprisonment and eventual escape, Dream, also known as Morpheus, goes on a quest for his lost objects of power. On his arduous journey Morpheus encounters Lucifer, John Constantine, and an all-powerful madman. This book also includes the story "The Sound of Her Wings," which introduces us to the pragmatic and perky goth girl Death. Collecting issues #1-8, this new edition of PRELUDES & NOCTURNES features the improved production values and coloring from the Absolute Edition.',
    },
    {
      title: "Moby Dick",
      author: "Herman Melville",
      img: "http://books.google.com/books/content?id=GL7BrQEACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE70PONzfYnKNannawhaPS3tnMEj1M50hZUCTbSEzH4cHXBWojNfIcp5mpN77vxYMYsQXUnwrkOO5I4Y-n6ZirXCompIHNR9KFkai5gXgRa6SFgzzpOa0yZJDE-tVtcvSatusvJ0i&source=gbs_api",
      rating: 4.8,
      category: "Classic Literature & Fiction",
      price: 8,
      stock: 5,
      publisher: "CreateSpace Independent Publishing Platform",
      maturityRating: "Recommended for all audiences",
      description:
        'Moby-Dick; or, The Whale is a novel by Herman Melville, in which Ishmael narrates the monomaniacal quest of Ahab, captain of the whaler Pequod, for revenge on the albino sperm whale Moby Dick, which on a previous voyage destroyed Ahab\'s ship and severed his leg at the knee. Although the novel was a commercial failure and out of print at the time of the author\'s death in 1891, its reputation grew immensely during the twentieth century. D. H. Lawrence called it "one of the strangest and most wonderful books in the world," and "the greatest book of the sea ever written." Moby-Dick is considered a Great American Novel and an outstanding work of the Romantic period in America and the American Renaissance. "Call me Ishmael" is one of world literature\'s most famous opening sentences. The product of a year and a half of writing, the book is dedicated to Nathaniel Hawthorne, "in token of my admiration for his genius," and draws on Melville\'s experience at sea, on his reading in whaling literature, and on literary inspirations such as Shakespeare and the Bible. The detailed and realistic descriptions of whale hunting and of extracting whale oil, as well as life aboard ship among a culturally diverse crew, are mixed with exploration of class and social status, good and evil, and the existence of God. In addition to narrative prose, Melville uses styles and literary devices ranging from songs, poetry and catalogs to Shakespearean stage directions, soliloquies and asides. The author changed the title at the very last moment in September 1851. The work first appeared as The Whale in London in October 1851, and then under its definitive title Moby-Dick in New York in November. The whale, however, appears in both the London and New York editions as "Moby Dick," with no hyphen. The British edition of five hundred copies was not reprinted during the author\'s life, the American of almost three thousand was reprinted three times at approximately 250 copies, the last reprinting in 1871. These figures are exaggerated because three hundred copies were destroyed in a fire at Harper\'s; only 3,200 copies were actually sold during the author\'s life.',
    },
    {
      title: "Introduction to Quantum Mechanics",
      author: "David J. Griffiths, Darrell F. Schroeter",
      img: "http://books.google.com/books/publisher/content?id=82FjDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72OSAkI3RKMi3HqIASQZvKY8sbutpXnsCHVmg6gwhs-2a1xlNya5uZhJCIBPxg8pIGUYSBeUHr7xZJzjWFJTrYRN2Z9tjAjbtwrxkfZBWpleqCfjNaDzplwfd0e545bXT-lU9Ri&source=gbs_api",
      rating: 4.6,
      category: "Science",
      price: 8,
      stock: 5,
      publisher: "Cambridge University Press",
      maturityRating: "Recommended for all audiences",
      description:
        "Changes and additions to the new edition of this classic textbook include a new chapter on symmetries, new problems and examples, improved explanations, more numerical problems to be worked on a computer, new applications to solid state physics, and consolidated treatment of time-dependent potentials.",
    },
    {
      title: "The Lord of the Rings",
      author: "J.R.R. Tolkien",
      img: "http://books.google.com/books/content?id=yl4dILkcqm4C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
      rating: 4.5,
      category: "Classic Literature & Fiction",
      price: 9,
      stock: 20,
      publisher: "Open Court",
      maturityRating: "NOT_MATURE",
      description:
        "A PBS Great American Read Top 100 Pick One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell by chance into the hands of the hobbit Bilbo Baggins. From Sauron's fastness in the Dark Tower of Mordor, his power spread far and wide. Sauron gathered all the Great Rings to him, but always he searched for the One Ring that would complete his dominion. When Bilbo reached his eleventy-first birthday he disappeared, bequeathing to his young cousin Frodo the Ruling Ring and a perilous quest: to journey across Middle-earth, deep into the shadow of the Dark Lord, and destroy the Ring by casting it into the Cracks of Doom. The Lord of the Rings tells of the great quest undertaken by Frodo and the Fellowship of the Ring: Gandalf the Wizard; the hobbits Merry, Pippin, and Sam; Gimli the Dwarf; Legolas the Elf; Boromir of Gondor; and a tall, mysterious stranger called Strider. This new edition includes the fiftieth-anniversary fully corrected text setting and, for the first time, an extensive new index. J.R.R. Tolkien (1892-1973), beloved throughout the world as the creator of The Hobbit, The Lord of the Rings, and The Silmarillion, was a professor of Anglo-Saxon at Oxford, a fellow of Pembroke College, and a fellow of Merton College until his retirement in 1959. His chief interest was the linguistic aspects of the early English written tradition, but while he studied classic works of the past, he was creating a set of his own.",
    },
    {
      title:
        "Studies in J. D. Salinger: Reviews, Essays, and Critiques of The Catcher in the Rye, and Other Fiction",
      author: "Marvin Laser, Norman Fruman",
      img: "http://books.google.com/books/content?id=yEhbAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
      rating: 5,
      category: "Fiction",
      price: 12,
      stock: 16,
      publisher: "Public",
      maturityRating: "NOT_MATURE",
      description:
        "Collects essays that look at J.D. Salinger's The Catcher in the Rye through a philosophical approach.",
    },
    {
      title: "Rayuela",
      author: "Julio Cortázar",
      img: "https://www.actualidadliteratura.com/wp-content/uploads/2017/02/An%C3%A1lisis-de-Rayuela-de-Julio-Cort%C3%A1zar.jpg",
      rating: 4,
      category: "Classic Literature & Fiction",
      price: 14,
      stock: 22,
      publisher: "Catedra Ediciones",
      maturityRating: "NOT_MATURE",
      description:
        "Por primera vez se edita «Rayuela» como un clásico de la novela contemporánea. Todo el conjunto de materiales que aporta esta edición (introducción, abundantes notas, plano, fotografías) servirán al lector para comprender mejor y disfrutar más con esta gran novela. Al aclararse tantas alusiones y técnicas narrativas, resplandece con más claridad el sentido profundo del relato: la búsqueda constante, el humor, el juego, la nostalgia de una verdadera vida, el paso soñado «de la tierra al cielo»...",
    },
    {
      title: "Mixing Secrets for the Small Studio",
      author: "Mike Senior",
      img: "https://images-na.ssl-images-amazon.com/images/I/41vyO5oQXAL._SX404_BO1,204,203,200_.jpg",
      rating: 4.7,
      category: "Science",
      price: 20,
      stock: 10,
      publisher: "Routledge",
      maturityRating: "Recommended for all audiences",
      description:
        "Mixing Secrets for the Small Studio is the best-selling primer for small-studio enthusiasts who want chart-ready sonics in a hurry. Drawing on the back-room strategies of more than 160 famous names, this entertaining and down-to-earth guide leads you step-by-step through the entire mixing process. On the way, you'll unravel the mysteries of every type of mix processing, from simple EQ and compression through to advanced spectral dynamics and fairy dust effects. User-friendly explanations introduce technical concepts on a strictly need-to-know basis, while chapter summaries and assignments are perfect for school and college use.",
    },
    {
      title: "El tesoro del pirata",
      author: "Núria Cussó Grau",
      img: "https://images-na.ssl-images-amazon.com/images/I/51L8b1qtrTL._SX403_BO1,204,203,200_.jpg",
      rating: 4.5,
      category: "Kids",
      price: 20,
      stock: 10,
      publisher: "Editorial el Pirata",
      maturityRating: "Recommended for all audiences",
      description:
        "Pedro es el pirata de seis años más valiente y astuto de los siete mares. A pesar de que aún es muy pequeño, se hace llamar Barbanegra, ¡igual que el pirata más peligroso de la historia!Hoy está triste. ¡No encuentra su tesoro favorito!El tesoro del pirata es el sexto cuento de la colección Aprender a leer en letra MAYÚSCULA e imprenta, con más de 100.000 ejemplares vendidos, que está ordenada en función de la dificultad lectora siendo el número 1 el más sencillo y el número 9 el más complejo. En cada página se encuentra el mismo texto: arriba en letra de imprenta y abajo en letra de PALO (mayúsculas). Permite trabajar la lectura en letra mayúscula y el cambio hacia la letra de imprenta.",
    },
    {
      title: "Just Be Jelly Hardcover",
      author: "Maddie Frost",
      img: "https://images-na.ssl-images-amazon.com/images/I/71p25ldU+FL.jpg",
      rating: 3,
      category: "Kids",
      price: 20,
      stock: 5,
      publisher: "Little, Brown Books for Young Readers",
      maturityRating: "Recommended for all audiences",
      description:
        "A groovy jellyfish helps a scared-of-everything sardine learn to take its problems in stride in this humorous picture book about wiggling your worries away. When a sardine who's scared of everything loses its handbook for staying safe in the sea, it goes into total panic mode. But right as big, scary shadows are surrounding it, the sardine runs into a jellyfish preaching the wisdom of wiggling your worries away. Try it! Wiggle up...wiggle down ...wiggle all around! When you're done, your problems might not seem so enormous—and those scary shadows might turn out to be friends!From the creator of Smug Seagull comes a funny, feel-good story about facing your fears (with the help of a few awesome dance moves)",
    },
    {
      title: "Are You a Cheeseburger?",
      author: "Monica Arnaldo",
      img: "https://images-na.ssl-images-amazon.com/images/I/81mMUmH0YgS.jpg",
      rating: 5,
      category: "Kids",
      price: 13.99,
      stock: 15,
      publisher: "Katherine Tegen Books",
      maturityRating: "Recommended for all audiences",
      description:
        "A Kids' Indie Next List pick! Laugh-out-loud humor and a tender friendship blossom in author-illustrator Monica Arnaldo’s charming picture book about a lonely raccoon and a glowing seed, and the world’s most important question: Can this seed grow cheeseburgers? Grub is a lonely racoon. Rumbling in the trash. Looking for food. Seed is, well, a seed! Patiently waiting in the trash. Hoping someone will plant it. When the two finally meet, they realize they might be able to help each other! Grub has just one big question first: What will Seed grow? Could Seed grow Grub’s favorite food, mouthwatering cheeseburgers? Seed isn’t sure what a cheeseburger is exactly, but . . . maybe! And so begins a hilarious friendship following two unlikely strangers learning more about the other and discovering the pressure that comes with fulfilling expectations. Author-illustrator Monica Arnaldo will leave readers giggling and clamoring for more in this charming story that celebrates the unexpected—and how the most special friendships bloom only when we are unapologetically ourselves.",
    },
    {
      title: "Time for School, Little Blue Truck",
      author: "Alice Schertle",
      img: "https://images-na.ssl-images-amazon.com/images/I/A1ee9JJRUCS.jpg",
      rating: 4.8,
      category: "Kids",
      price: 10.77,
      stock: 35,
      publisher: "HMH Books for Young Readers",
      maturityRating: "Recommended for all audiences",
      description:
        "Ride along to school with the #1 New York Times best-selling Little Blue Truck and meet Blue's new friend: a bright yellow school bus. Beep-beep! Little Blue Truck and his good friend Toad are excited to meet a bright yellow school bus on the road. They see all the little animals lined up in the school bus’s many windows, and Blue wishes he could be a school bus too. What a fun job—but much too big for a little pickup like Blue. Or is it? When somebody misses the bus, it’s up to Blue to get his friend to school on time. Beep! Beep! Vroom! Also enjoy Blue’s bedtime ride in Good Night, Little Blue Truck and his trip to the city in Little Blue Truck Leads the Way.",
    },
    {
      title: "Great Circle: A novel",
      author: "Conrad Aiken",
      img: "https://m.media-amazon.com/images/I/51VzvMROz9L.jpg",
      rating: 5,
      category: "Classic Literature & Fiction",
      price: 25,
      stock: 17,
      publisher: "Open Road Media",
      maturityRating: "Recommended for all audiences",
      description:
        "The train races from New York to Boston. For Andrew Cather, it is much too fast. He will return home three days early, and he is both terrified and intrigued by what he may find there. He pictures himself unlocking the door to his quiet Cambridge house, padding silently through its darkened halls, and finally discovering the thing he both fears and yearns to see: his wife in the arms of another man. Cather knows that what he finds in Cambridge may destroy his life, yet finally set him free. A masterful portrait of an average man at the edge of a shocking precipice, Great Circle is a triumph of psychological realism. One of Sigmund Freud’s favorite novels, it is a probing exploration of the secrets of consciousness.",
    },
    {
      title: "Mi Gran Libro de experimentos",
      author: "Mar Benegas",
      img: "https://images-na.ssl-images-amazon.com/images/I/81YOoodAneL.jpg",
      rating: 4.6,
      category: "Kids",
      price: 18,
      stock: 18,
      publisher: "Susaeta",
      maturityRating: "ALL",
      description:
        "Convierte un huevo en una pelota o unos fideos en verdaderos bailarines, fabrica tu propia nave espacial o tu bosque mágico de cristales, consigue que llueva o que la arena no se moje, manda mensajes en tinta invisible que solo otro científico como tú logre leer en secreto... ¡No es magia, es ciencia! ¡Atrévete a convertirte en un pequeño gran científico!",
    },
    {
      title: "Harry Potter Coloring Book",
      author: "Scholastic",
      img: "https://images-na.ssl-images-amazon.com/images/I/81uHJU1iy9L.jpg",
      rating: 4.8,
      category: "Kids",
      price: 20,
      stock: 25,
      publisher: "Scholastic Inc.",
      maturityRating: "8 years and up",
      description:
        "Unleash your creativity and escape to one of the most beloved series of all time. From the heraldry of the four Hogwarts houses to the extravagant wares of Weasleys Wizard Wheezes, the world of Harry Potter overflows with radiant color. Filled with intricate illustrations and elaborate designs used in the making of the Harry Potter films, this book invites you to imbue the wizarding world with color in your own explorations of Hogwarts Castle, the Forbidden Forest, and much more. You will also find pages of magical creatures and iconic scenes from the films, from the Sorting Ceremony in Harrys first year, to the unforgettable final battle between Harry and Lord Voldemort, as well as some of the marvelous props used in the movies, such as The Quibbler, Quidditch World Cup posters, and the Triwizard Cup. Also includes sixteen pages of full-color art from the movies to inspire you as you draw.",
    },
    {
      title: "Fallout: The Vault Dweller's Official Cookbook",
      author: "Victoria Rosenthal",
      img: "https://images-na.ssl-images-amazon.com/images/I/8133p-u2BaL.jpg",
      rating: 4.8,
      category: "Cooking",
      price: 32,
      stock: 23,
      publisher: "Insight Editions",
      maturityRating: "ALL",
      description:
        "Craft your own glass of Nuka-Cola, a bowl of BlamCo Mac & Cheese, and more with the recipes in Fallout: The Official Cookbook. Based on the irradiated delicacies of the world of Bethesda Entertainment’s Fallout, this Vault-Tec–approved cookbook provides fans of the award-winning series with recipes inspired by their favorite Fallout foods. Whip up tasty versions of the Mirelurk egg omelette, throw some deathclaw meat on the grill, and re-create BlamCo Mac & Cheese with Fallout: The Official Cookbook.",
    },
    {
      title: "Swann's Way: In Search of Lost Time, Volume One",
      author: "Marcel Proust",
      img: "https://images-na.ssl-images-amazon.com/images/I/51b6H4g2dcL.jpg",
      rating: 4.4,
      category: "Classic Literature & Fiction",
      price: 12,
      stock: 6,
      publisher: "Independently published",
      maturityRating: "MATURE",
      description:
        "A new, beautifully laid-out edition of Marcel Proust's 1922 classic novel, the first volume of his In Search of Lost Time series (also known as, The Remembrance of Things Past). This edition is based on the 1922 translation by C.K. Scott Moncrieff (1889-1930).",
    },
    {
      title: "The Invisible Life of Addie LaRue",
      author: "V. E. Schwab",
      img: "https://images-na.ssl-images-amazon.com/images/I/91Ql48Y0mqL.jpg",
      rating: 4.5,
      category: "ALL",
      price: 11,
      stock: 8,
      publisher: "Tor Books: Illustrated edition",
      maturityRating: "MATURE",
      description:
        "France, 1714: in a moment of desperation, a young woman makes a Faustian bargain to live forever―and is cursed to be forgotten by everyone she meets. Thus begins the extraordinary life of Addie LaRue, and a dazzling adventure that will play out across centuries and continents, across history and art, as a young woman learns how far she will go to leave her mark on the world. But everything changes when, after nearly 300 years, Addie stumbles across a young man in a hidden bookstore and he remembers her name.",
    },
    {
      title: "The Midnight Library: A Novel",
      author: "Matt Haig",
      img: "https://images-na.ssl-images-amazon.com/images/I/81YzHKeWq7L.jpg",
      rating: 4.4,
      category: "Science Fiction & Fantasy",
      price: 14,
      stock: 24,
      publisher: "Viking",
      maturityRating: "MATURE",
      description:
        "Somewhere out beyond the edge of the universe there is a library that contains an infinite number of books, each one the story of another reality. One tells the story of your life as it is, along with another book for the other life you could have lived if you had made a different choice at any point in your life. While we all wonder how our lives might have been, what if you had the chance to go to the library and see for yourself? Would any of these other lives truly be better? In The Midnight Library, Matt Haig's enchanting blockbuster novel, Nora Seed finds herself faced with this decision. Faced with the possibility of changing her life for a new one, following a different career, undoing old breakups, realizing her dreams of becoming a glaciologist; she must search within herself as she travels through the Midnight Library to decide what is truly fulfilling in life, and what makes it worth living in the first place.",
    },
    {
      title: "The Alchemist, 25th Anniversary",
      author: "Paulo Coelho",
      img: "https://images-na.ssl-images-amazon.com/images/I/51kcX5PpaZL.jpg",
      rating: 4.7,
      category: "Science Fiction & Fantasy",
      price: 13,
      stock: 4,
      publisher: "HarperOne",
      maturityRating: "ALL",
      description:
        "A special 25th anniversary edition of the extraordinary international bestseller, including a new Foreword by Paulo Coelho. Combining magic, mysticism, wisdom and wonder into an inspiring tale of self-discovery,The Alchemist has become a modern classic, selling millions of copies around the world and transforming the lives of countless readers across generations. Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined. Santiago's journey teaches us about the essential wisdom of listening to our hearts, of recognizing opportunity and learning to read the omens strewn along life's path, and, most importantly, to follow our dreams.",
    },
    {
      title: "Fahrenheit 451",
      author: "Ray Bradbury",
      img: "https://images-na.ssl-images-amazon.com/images/I/71OFqSRFDgL.jpg",
      rating: 4.6,
      category: "Science Fiction & Fantasy",
      price: 10,
      stock: 12,
      publisher: "Simon & Schuster",
      maturityRating: "MATURE",
      description:
        "Guy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television “family.” But when he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didn’t live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television, Montag begins to question everything he has ever known.",
    },
    {
      title: "Rich Dad Poor Dad",
      author: "Robert T. Kiyosaki",
      img: "https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg",
      rating: 4.7,
      category: "Business & Money",
      price: 8,
      stock: 12,
      publisher: "Plata Publishing",
      maturityRating: "MATURE",
      description: "Business & Money",
    },
    {
      title: "The Intelligent Investor: The Definitive Book on Value Investing.",
      author: "Benjamin Graham",
      img: "https://images-na.ssl-images-amazon.com/images/I/91yj3mbz4JL.jpg",
      rating: 4.7,
      category: "Business & Money",
      price: 15,
      stock: 16,
      publisher: "Harper Business",
      maturityRating: "Recommended for all audiences",
      description: `This classic text is annotated to update Graham's timeless wisdom for today's market conditions... The greatest investment advisor of the twentieth century, Benjamin Graham, taught and inspired people worldwide. Graham's philosophy of "value investing" -- which shields investors from substantial error and teaches them to develop long-term strategies -- has made The Intelligent Investor the stock market bible ever since its original publication in 1949. Over the years, market developments have proven the wisdom of Graham's strategies. While preserving the integrity of Graham's original text, this revised edition includes updated commentary by noted financial journalist Jason Zweig, whose perspective incorporates the realities of today's market, draws parallels between Graham's examples and today's financial headlines, and gives readers a more thorough understanding of how to apply Graham's principles.`,
    },
    {
      title: "Noise: A Flaw in Human Judgment",
      author: "Daniel Kahneman",
      img: "https://images-na.ssl-images-amazon.com/images/I/81G92Rdj7FS.jpg",
      rating: 4.4,
      category: "Business & Money",
      price: 19,
      stock: 7,
      publisher: "Little, Brown Spark",
      maturityRating: "MATURE",
      description: `From the Nobel Prize-winning author of Thinking, Fast and Slow and the coauthor of Nudge, a revolutionary exploration of why people make bad judgments and how to make better ones--"a tour de force” (New York Times). Imagine that two doctors in the same city give different diagnoses to identical patients—or that two judges in the same courthouse give markedly different sentences to people who have committed the same crime. Suppose that different interviewers at the same firm make different decisions about indistinguishable job applicants—or that when a company is handling customer complaints, the resolution depends on who happens to answer the phone. Now imagine that the same doctor, the same judge, the same interviewer, or the same customer service agent makes different decisions depending on whether it is morning or afternoon, or Monday rather than Wednesday. These are examples of noise: variability in judgments that should be identical. In Noise, Daniel Kahneman, Olivier Sibony, and Cass R. Sunstein show the detrimental effects of noise in many fields, including medicine, law, economic forecasting, forensic science, bail, child protection, strategy, performance reviews, and personnel selection. Wherever there is judgment, there is noise. Yet, most of the time, individuals and organizations alike are unaware of it. They neglect noise. With a few simple remedies, people can reduce both noise and bias, and so make far better decisions. Packed with original ideas, and offering the same kinds of research-based insights that made Thinking, Fast and Slow and Nudge groundbreaking New York Times bestsellers, Noise explains how and why humans are so susceptible to noise in judgment—and what we can do about it.`,
    },
    {
      title: "The Premonition: A Pandemic Story",
      author: "Michael Lewis",
      img: "https://images-na.ssl-images-amazon.com/images/I/51y4sn12xoS.jpg",
      rating: 5,
      category: "Business & Money",
      price: 14,
      stock: 8,
      publisher: "W. W. Norton & Company",
      maturityRating: "MATURE",
      description: `For those who could read between the lines, the censored news out of China was terrifying. But the president insisted there was nothing to worry about. Fortunately, we are still a nation of skeptics. Fortunately, there are those among us who study pandemics and are willing to look unflinchingly at worst-case scenarios. Michael Lewis’s taut and brilliant nonfiction thriller pits a band of medical visionaries against the wall of ignorance that was the official response of the Trump administration to the outbreak of COVID-19. The characters you will meet in these pages are as fascinating as they are unexpected. A thirteen-year-old girl’s science project on transmission of an airborne pathogen develops into a very grown-up model of disease control. A local public-health officer uses her worm’s-eye view to see what the CDC misses, and reveals great truths about American society. A secret team of dissenting doctors, nicknamed the Wolverines, has everything necessary to fight the pandemic: brilliant backgrounds, world-class labs, prior experience with the pandemic scares of bird flu and swine flu…everything, that is, except official permission to implement their work. Michael Lewis is not shy about calling these people heroes for their refusal to follow directives that they know to be based on misinformation and bad science. Even the internet, as crucial as it is to their exchange of ideas, poses a risk to them. They never know for sure who else might be listening in.`,
    },
    {
      title:
        "The Cult of We: WeWork, Adam Neumann, and the Great Startup Delusion",
      author: "Eliot Brown et al.",
      img: "https://m.media-amazon.com/images/I/814jHH+fifL._AC_SX960_SY720_.jpg",
      rating: 4,
      category: "Business & Money",
      price: 20,
      stock: 17,
      publisher: "Crown",
      maturityRating: "MATURE",
      description: `“A juicy investigation into one of Silicon Valley’s most-hyped fallen unicorns.”—Time (Best Books of Summer 2021). The definitive inside story of WeWork, its audacious founder, and what its epic unraveling says about a financial system drunk on the elixir of Silicon Valley innovation—from the Wall Street Journal correspondents (recently featured in the WeWork Hulu documentary) whose scoop-filled reporting hastened the company’s downfall. WeWork would be worth $10 trillion, more than any other company in the world. It wasn’t just an office space provider. It was a tech company—an AI startup, even. Its WeGrow schools and WeLive residences would revolutionize education and housing. One day, mused founder Adam Neumann, a Middle East peace accord would be signed in a WeWork. The company might help colonize Mars. And Neumann would become the world’s first trillionaire. This was the vision of Neumann and his primary cheerleader, SoftBank’s Masayoshi Son. In hindsight, their ambition for the company, whose primary business was subletting desks in slickly designed offices, seems like madness. Why did so many intelligent people—from venture capitalists to Wall Street elite—fall for the hype? And how did WeWork go so wrong? In little more than a decade, Neumann transformed himself from a struggling baby clothes salesman into the charismatic, hard-partying CEO of a company worth $47 billion—on paper. With his long hair and feel-good mantras, the six-foot-five Israeli transplant looked the part of a messianic truth teller. Investors swooned, and billions poured in. Neumann dined with the CEOs of JPMorgan and Goldman Sachs, entertaining a parade of power brokers desperate to get a slice of what he was selling: the country’s most valuable startup, a once-in-a-lifetime opportunity and a generation-defining moment. Soon, however, WeWork was burning through cash faster than Neumann could bring it in. From his private jet, sometimes clouded with marijuana smoke, he scoured the globe for more capital. Then, as WeWork readied a Hail Mary IPO, it all fell apart. Nearly $40 billion of value vaporized in one of corporate America’s most spectacular meltdowns. Peppered with eye-popping, never-before-reported details, The Cult of We is the gripping story of careless and often absurd people—and the financial system they have made.`,
    },
    {
      title: "Will",
      author: "Mark Manson",
      img: "https://images-na.ssl-images-amazon.com/images/I/91t9XuSD6oS.jpg",
      rating: 2,
      category: "Biography",
      price: 20,
      stock: 4,
      publisher: "Penguin Press",
      maturityRating: "MATURE",
      description: `Will Smith’s transformation from a fearful child in a tense West Philadelphia home to one of the biggest rap stars of his era and then one of the biggest movie stars in Hollywood history, with a string of box office successes that will likely never be broken, is an epic tale of inner transformation and outer triumph, and Will tells it astonishingly well. But it's only half the story. Will Smith thought, with good reason, that he had won at life: not only was his own success unparalleled, his whole family was at the pinnacle of the entertainment world. Only they didn't see it that way: they felt more like star performers in his circus, a seven-days-a-week job they hadn't signed up for. It turned out Will Smith's education wasn't nearly over. This memoir is the product of a profound journey of self-knowledge, a reckoning with all that your will can get you and all that it can leave behind. Written with the help of Mark Manson, author of the multi-million-copy bestseller The Subtle Art of Not Giving a F*ck, Will is the story of how one person mastered his own emotions, written in a way that can help everyone else do the same. Few of us will know the pressure of performing on the world's biggest stages for the highest of stakes, but we can all understand that the fuel that works for one stage of our journey might have to be changed if we want to make it all the way home. The combination of genuine wisdom of universal value and a life story that is preposterously entertaining, even astonishing, puts Will the book, like its author, in a category by itself.`,
    },
    {
      title: "Somebody's Daughter: A Memoir",
      author: "Ashley C. Ford",
      img: "https://images-na.ssl-images-amazon.com/images/I/714c3+WWXOS.jpg",
      rating: 4,
      category: "Biography",
      price: 20,
      stock: 6,
      publisher: "Flatiron Books: An Oprah Book",
      maturityRating: "MATURE",
      description: `Through poverty, adolescence, and a fraught relationship with her mother, Ashley C. Ford wishes she could turn to her father for hope and encouragement. There are just a few problems: he’s in prison, and she doesn’t know what he did to end up there. She doesn’t know how to deal with the incessant worries that keep her up at night, or how to handle the changes in her body that draw unwanted attention from men. In her search for unconditional love, Ashley begins dating a boy her mother hates. When the relationship turns sour, he assaults her. Still reeling from the rape, which she keeps secret from her family, Ashley desperately searches for meaning in the chaos. Then, her grandmother reveals the truth about her father’s incarceration . . . and Ashley’s entire world is turned upside down. Somebody’s Daughter steps into the world of growing up a poor Black girl in Indiana with a family fragmented by incarceration, exploring how isolating and complex such a childhood can be. As Ashley battles her body and her environment, she embarks on a powerful journey to find the threads between who she is and what she was born into, and the complicated familial love that often binds them.`,
    },
    {
      title: "The Name of the Wind",
      author: "Patrick Rothfuss",
      img: "http://books.google.com/books/content?id=BcG2dVRXKukC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
      rating: 4,
      category: "Fiction",
      price: 5,
      stock: 10,
      publisher: "Hachette UK",
      maturityRating: "NOT_MATURE",
      description: `This is a magnificent book' Anne McCaffrey 'I was reminded of Ursula K. Le Guin, George R. R. Martin, and J. R. R. Tolkein, but never felt that Rothfuss was imitating anyone' THE TIMES 'I have stolen princesses back from sleeping barrow kings. I burned down the town of Trebon. I have spent the night with Felurian and left with both my sanity and my life. I was expelled from the University at a younger age than most people are allowed in. I tread paths by moonlight that others fear to speak of during day. I have talked to Gods, loved women, and written songs that make the minstrels weep. My name is Kvothe. You may have heard of me' So begins the tale of Kvothe - currently known as Kote, the unassuming innkeepter - from his childhood in a troupe of traveling players, through his years spent as a near-feral orphan in a crime-riddled city, to his daringly brazen yet successful bid to enter a difficult and dangerous school of magic. In these pages you will come to know Kvothe the notorious magician, the accomplished thief, the masterful musician, the dragon-slayer, the legend-hunter, the lover, the thief and the infamous assassin.`,
    },
    {
      title: "The Wise Man's Fear",
      author: "Patrick Rothfuss",
      img: "http://books.google.com/books/content?id=qUW5js7ZD7UC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
      rating: 4,
      category: "Fiction",
      price: 5,
      stock: 4,
      publisher: "Hachette UK",
      maturityRating: "NOT_MATURE",
      description:
        "'I just love the world of Patrick Rothfuss' Lin-Manuel Miranda 'He's bloody good, this Rothfuss guy' George R R Martin Sequel to the extraordinary THE NAME OF THE WIND, THE WISE MAN'S FEAR is the second instalment of this superb fantasy trilogy from Patrick Rothfuss. This is the most exciting fantasy series since George R. R. Martin's A SONG OF ICE AND FIRE, and a must-read for all fans of HBO's GAME OF THRONES. Picking up the tale of Kvothe Kingkiller once again, we follow him into exile, into political intrigue, courtship, adventure, love and magic ... and further along the path that has turned Kvothe, the mightiest magician of his age, a legend in his own time, into Kote, the unassuming pub landlord. Packed with as much magic, adventure and home-grown drama as THE NAME OF THE WIND, this is a sequel in every way the equal to its predecessor and a must-read for all fantasy fans. Readable, engaging and gripping THE WISE MAN'S FEAR is the biggest and the best new fantasy novel out there.",
    },
    {
      title: "Los secretos de la mente millonaria",
      author: "T.Harv Eker",
      img: "http://books.google.com/books/content?id=_2ssDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
      rating: 2,
      category: "Self-Help",
      price: 6,
      stock: 5,
      publisher: "EDITORIAL SIRIO S.A",
      maturityRating: "NOT_MATURE",
      description:
        "Todos tenemos un patrón personal del dinero arraigado en nuestro subconsciente, y es este patrón, más que cualquier otra cosa, lo que determinará nuestra vida financiera. Puedes saberlo todo sobre mercadotecnia, ventas, negociaciones, acciones, propiedad inmobiliaria y finanzas en general, pero si tu patrón del dinero no está programado para el éxito nunca tendrás mucho dinero; y si, de algún modo lo consigues, ¡lo perderás con gran facilidad! La buena noticia es que ahora, aplicando las sencillas instrucciones contenidas en este libro, puedes programar de nuevo tu patrón del dinero para que te lleve al éxito económico de una forma natural y automática. ¡Los resultados te sorprenderán",
    },
    {
      title: "Frankenstein",
      author: "Mary Shelley",
      img: "http://books.google.com/books/content?id=gj3lDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
      rating: 4.8,
      category: "Fiction",
      price: 8.75,
      stock: 5,
      publisher: "Zeuk Media",
      maturityRating: "NOT_MATURE",
      description:
        "Mary Shelley comenzó a escribir Frankenstein cuando solo tenía dieciocho años. Inmediatamente un thriller gótico, un romance apasionado y una historia de advertencia sobre los peligros de la ciencia, Frankenstein cuenta la historia del comprometido estudiante de ciencias Victor Frankenstein. Obsesionado con descubrir la causa de la generación y la vida y con la animación de la materia sin vida, Frankenstein reúne a un ser humano a partir de partes del cuerpo robadas, pero; Al darle vida, retrocede horrorizado ante la horrorosa criatura. Atormentada por el aislamiento y la soledad, la criatura una vez inocente se convierte en malvada y desata una campaña de venganza asesina contra su creador, Frankenstein.Frankenstein, un éxito de ventas instantáneo y un importante antepasado de los géneros de terror y ciencia ficción, no solo cuenta una historia aterradora, sino que también plantea preguntas profundas e inquietantes sobre la naturaleza misma de la vida y el lugar de la humanidad dentro del cosmos: ¿Qué hace? significa ser humano? ¿Qué responsabilidades tenemos el uno con el otro? ¿Hasta dónde podemos llegar para alterar la naturaleza? En nuestra era, llena de noticias sobre donación de órganos, ingeniería genética y bioterrorismo, estas preguntas son más relevantes que nunca.",
    },
    {
      title: "Padre rico. Padre pobre",
      author: "Robert T. Kiyosaki",
      img: "http://books.google.com/books/content?id=NEz44me8a5MC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
      rating: 4.8,
      category: "Business & Economics",
      price: 8,
      stock: 5,
      publisher: "Aguilar",
      maturityRating: "NOT_MATURE",
      description:
        'Basado en el principio de que los bienes que generan ingreso siempre dan mejores resultados que los trabajos tradicionales, Robert Kiyosaki explica cómo pueden adquirirse dichos bienes para, eventualmente, olvidarse de trabajar. El libro #1 de finanzas personales. Con un estilo claro y ameno, este libro te pondrá en el camino directo al éxito financiero y así lograrás que el dinero trabaje para ti. Padre rico Padre pobre es el bestseller que revolucionó la forma de entender las finanzas personales. El autor y conferencista Robert Kiyosaki desarrolló una perspectiva económica única a partir de la exposición que tuvo a dos influencias: su propio padre, altamente educado pero muy inestable y el padre multimillonario, sin educación universitaria, de su mejor amigo. Los problemas monetarios que su Padre pobre experimentó toda la vida (con cheques mensuales muy respetables pero nunca suficientes) rompían con lo que le comunicaba su Padre rico: que la clase pobre y la clase media trabajan por dinero pero la clase alta, hace que el dinero trabaje para ellos. Kiyosaki presenta la filosofía detrás de esta relación excepcional con el dinero. Este libro aboga de manera convincente por el tipo de conocimiento financiero que nunca se enseña en las escuelas. Padre rico padre pobre lo ayudará a: -Derribar el mito de que usted necesita tener un ingreso elevado para hacerse rico. -Desafiar la creencia de que su casa es una inversión. -Mostrar a los padres por qué no confiar en el sistema escolar para la enseñanza de sus hijos acerca del dinero. -Definir de una vez y para siempre qué es una inversión y qué es una obligación. -Mostrar qué enseñar a los hijos acerca del dinero para su futuro éxito financiero. Lo que ha dicho la crítica: "Padre rico padre pobre es el punto de partida para quien quiera tomar el control de su futuro financiero." -USA Today',
    },
    {
      title: "Los ojos del perro siberiano",
      author: "Antonio Santa Ana",
      img: "http://books.google.com/books/content?id=r_n3OQf9nCYC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
      rating: 4.8,
      category: "AIDS (Disease)",
      price: 3.75,
      stock: 5,
      publisher: "Editorial Norma",
      maturityRating: "NOT_MATURE",
      description:
        "Nos quedamos un rato en silencio, envueltos en el perfume de las hierbas. Hasta que le pregunte. -Por que nunca hablamos de Ezequiel? Apoyo las cosas en el piso con mucha calma. Estiro su mano como para acariciarme. Me miro. Bajo la mano. Luego la vista y dijo en un susurro: - Hay cosas de las que es mejor no hablar.",
    },
    {
      title: "El ABC para crear un equipo de negocios exitoso",
      author: "Blair Singer",
      img: "http://books.google.com/books/content?id=mZbOAGL2mEYC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
      rating: 4.8,
      category: "Business & Economics",
      price: 10,
      stock: 5,
      publisher: "AGUILAR",
      maturityRating: "NOT_MATURE",
      description:
        "Un libro que te dará una gran ventaja sobre el mercado y más aún, sobre el desempeño de tu gente. El código de honor invisible que transforma a grupos de personas en equipos campeones. Prólogo de Robert Kiyosaki. Descubre cómo atraer a los mejores jugadores para tu negocio, garantizar que todos los miembros de tu equipo tengan un máximo desempeño, transformar a las personas ordinarias en campeones, infundir lealtad y confianza en tu equipo para que permanezca unido bajo presión, eliminar los estresantes roces personales en tu empresa y crear equipos de campeonato en tu lugar de trabajo, tu comunidad y tu hogar. El ABC para crear un equipo de negocios exitoso te ayudará a: - Atraer a los mejores jugadores para tu negocio; - Garantizar que todos los miembros de tu equipo tengan un máximo desempeño; - Transformar a las personas ordinarias en campeones; - Infundir lealtad y con?anza en tu equipo para que permanezca unido bajo presión; - Eliminar los estresantes roces personales en tu empresa; - Usar la presión como un aliado para generar resultados extraordinarios; y. - Crear equipos de campeonato en tu lugar de trabajo. tu comunidad y tu hogar.",
    },
    {
      title: "Véndele a la mente, no a la gente",
      author: "Jürgen Klaric",
      img: "http://books.google.com/books/content?id=7pZHDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
      rating: 4.8,
      category: "Business & Economics",
      price: 7.5,
      stock: 5,
      publisher: "Paidos México",
      maturityRating: "NOT_MATURE",
      description:
        "HOY VENDER ES DEMASIADO DIFÍCIL. NO SABEMOS POR QUÉ COMPRAMOS En un mundo competitivo, donde casi todos los servicios y productos se están volviendo un commodity, llega la ciencia más revolucionaria del mercado. Aprende de forma práctica y entretenida cómo vender más hablando menos. El 85% de todo lo que el consumidor adquiere lo hace de forma inconsciente. Los seres humanos no saben por qué compran lo que compran; con neuroventas descubriremos cómo hacer que elijan tu producto o servicio sin hacer grandes esfuerzos. CIENTOS DE EMPRESAS Líderes en veinte países venden con este conocimiento. El autor junto con su equipo científico, con sede en cinco países, ha transformado la cultura y los resultados de equipos comerciales y de ventas en cientos de empresas como Amway, IKEA, Kimberly Clark, Big Cola, Seguros Maphre, Telefónica Movistar, Telmex, Claro, Sony, Samsung, Nestlé, Bayer, General Motors y otros grandes grupos del sector inmobiliario y publicitario.",
    },
    {
      title: "The Sandman Vol. 2: The Doll's House",
      author: "Neil Gaiman",
      img: "https://http2.mlstatic.com/D_NQ_NP_842872-MLA46239845318_062021-O.webp",
      rating: 4.9,
      category: "Comics & Graphic Novels",
      price: 12.99,
      stock: 9,
      publisher: "DC",
      maturityRating: "Recommended for all audiences",
      description:
        'NEW YORK TIMES bestselling author Neil Gaiman\'s transcendent series SANDMAN is often hailed as the definitive Vertigo title and one of the finest achievements in graphic storytelling. Gaiman created an unforgettable tale of the forces that exist beyond life and death by weaving ancient mythology, folklore and fairy tales with his own distinct narrative vision. In PRELUDES & NOCTURNES, an occultist attempting to capture Death to bargain for eternal life traps her younger brother Dream instead. After his seventy-year imprisonment and eventual escape, Dream, also known as Morpheus, goes on a quest for his lost objects of power. On his arduous journey Morpheus encounters Lucifer, John Constantine, and an all-powerful madman. This book also includes the story "The Sound of Her Wings," which introduces us to the pragmatic and perky goth girl Death. Collecting issues #1-8, this new edition of PRELUDES & NOCTURNES features the improved production values and coloring from the Absolute Edition.',
    },
    {
      title: "Sabiduría",
      author: "Paulo Coelho",
      img: "http://books.google.com/books/content?id=PN6dtgAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
      rating: 4.8, //
      category: "Reference",
      price: 5.6,
      stock: 5, //
      publisher: "Planeta",
      maturityRating: "NOT_MATURE",
      description:
        "«Nuestra vejez dependerá de la manera en que vivamos. Podemos acabar como una ciudad fantasma. O como un árbol generoso – que sigue siendo importante, incluso después de no poder tenerse en pie. » Crónica – Reflexiones sobre la edad",
    },
    {
      title: "Cien años de Soledad",
      author: "Gabriel Garcia Marquez",
      img: "https://http2.mlstatic.com/D_NQ_NP_962138-MLA46347486689_062021-O.webp",
      rating: 4.8,
      category: "Classic Literature & Fiction",
      price: 14,
      stock: 25,
      publisher: "Penguin Books Ltd",
      maturityRating: "Recommended for all audiences",
      description: `Many years later, as he faced the firing squad, Colonel Aureliano Buendia was to remember that distant afternoon when his father took him to discover ice.'
  Gabriel Garcia Marquez's great masterpiece is the story of seven generations of the Buendia family and of Macondo, the town they built. Though little more than a settlement surrounded by mountains, Macondo has its wars and disasters, even its wonders and its miracles. A microcosm of Columbian life, its secrets lie hidden, encoded in a book, and only Aureliano Buendia can fathom its mysteries and reveal its shrouded destiny. 
  Blending political reality with magic realism, fantasy and comic invention, One Hundred Years of Solitude is one of the most daringly original works of the twentieth century.`,
    },
    {
      title: "El amor en los tiempos del colera",
      author: "Gabriel Garcia Marquez",
      img: "https://images.cdn1.buscalibre.com/fit-in/360x360/64/68/6468bf35944e8d5a2a45e7ac4ea8bd79.jpg",
      rating: 4.3,
      category: "Classic Literature & Fiction",
      price: 12,
      stock: 20,
      publisher: "Penguin Books Ltd ",
      maturityRating: "Recommended for all audiences",
      description: `It was inevitable: the scent of bitter almonds always reminded him of the fate of unrequited love'
  Fifty-one years, nine months and four days have passed since Fermina Daza rebuffed hopeless romantic Florentino Ariza's impassioned advances and married Dr Juvenal Urbino instead. During that half-century, Flornetino has fallen into the arms of many delighted women, but has loved none but Fermina.
  When Fermina's husband is killed trying to retrieve his pet parrot from a mango tree, Florentino seizes his chance to declare his enduring love. But can young love find new life in the twilight of their lives?`,
    },
    {
      title: "El coronel no tiene quien le escriba",
      author: "Gabriel Garcia Marquez",
      img: "https://http2.mlstatic.com/D_NQ_NP_685580-MLA46399955733_062021-O.webp",
      rating: 4.3,
      category: "Classic Literature & Fiction",
      price: 12,
      stock: 20,
      publisher: "Penguin Books",
      maturityRating: "Recommended for all audiences",
      description: `Fridays are different. Every other day of the week, the Colonel and his ailing wife fight a constant battle against poverty and monotony, scraping together the dregs of their savings for the food and medicine that keeps them alive. But on Fridays the postman comes - and that sets a fleeting wave of hope rushing through the Colonel's ageing heart.
  For fifteen years he's watched the mail launch come into harbour, hoping he'll be handed an envelope containing the army pension promised to him all those years ago. Whilst he waits for the cheque, his hopes are pinned on his prize bird and the upcoming cockfighting season. But until then the bird - like the Colonel and his wife - must somehow be fed.`,
    },
    {
      title: "El Aleph",
      author: "Jorge Luis Borges",
      img: "https://images.cdn3.buscalibre.com/fit-in/360x360/ce/9c/ce9ce81f8c28fe9590443f1d2eafa159.jpg",
      rating: 4.3,
      category: "Classic Literature & Fiction",
      price: 13,
      stock: 20,
      publisher: "Sudamericana",
      maturityRating: "Recommended for all audiences",
      description: `Borges' stories have a deceptively simple, almost laconic style. In maddeningly ingenious stories that play with the very form of the short story, Borges returns again and again to his themes: dreams, labyrinths, mirrors, infinite libraries, the manipulations of chance, gaucho knife-fighters, transparent tigers and the elusive nature of identity itself`,
    },
  
    {
      title: "La tregua",
      author: "Mario Benedetti",
      img: "https://images.cdn3.buscalibre.com/fit-in/360x360/53/7c/537c3e810b4279c06134d03c0d62db8a.jpg",
      rating: 4.3,
      category: "Classic Literature & Fiction",
      price: 12,
      stock: 20,
      publisher: "Penguin Books ",
      maturityRating: "Recommended for all audiences",
      description: `Forty-nine, with a kind face, no serious ailments (apart from varicose veins on his ankles), a good salary and three moody children, widowed accountant Martin Santome is about to retire. He assumes he'll take up gardening, or the guitar, or whatever retired people do. What he least expects is to fall passionately in love with his shy young employee Laura Avellaneda. As they embark upon an affair, happy and irresponsible, Martin begins to feel the weight of his quiet existence lift - until, out of nowhere, their joy is cut short. 
  The intimate, heartbreaking diary of an ordinary man who is reborn when he falls in love one final time, this beloved Latin American novel has been translated into twenty languages and sold millions of copies worldwide, and is now published in Penguin Classics for the first time.`,
    },
    {
      title: "La Sombra del viento ",
      author: "Carlos Ruiz Zafon",
      img: "https://images.cdn2.buscalibre.com/fit-in/360x360/76/57/765701bf5a03886bc18338cf69a77aac.jpg",
      rating: 4.3,
      category: "Classic Literature & Fiction",
      price: 12,
      stock: 20,
      publisher: "Planeta",
      maturityRating: "Recommended for all audiences",
      description: `The Shadow of the Wind is a stunning literary thriller in which the discovery of a forgotten book leads to a hunt for an elusive author who may or may not still be alive...
  Hidden in the heart of the old city of Barcelona is the 'Cemetery of Lost Books', a labyrinthine library of obscure and forgotten titles that have long gone out of print. To this library, a man brings his 10-year-old son Daniel one cold morning in 1945. Daniel is allowed to choose one book from the shelves and pulls out 'The Shadow of the Wind' by Julian Carax.
  But as he grows up, several people seem inordinately interested in his find. Then, one night, as he is wandering the old streets once more, Daniel is approached by a figure who reminds him of a character from the book, a character who turns out to be the devil. This man is tracking down every last copy of Carax's work in order to burn them. What begins as a case of literary curiosity turns into a race to find out the truth behind the life and death of Julian Carax and to save those he left behind...`,
    },
    {
      title: "El Prisionero del cielo",
      author: "Carlos Ruiz Zafon",
      img: "https://images.cdn3.buscalibre.com/fit-in/360x360/95/25/9525ccafdee5e37299fe19a4df091059.jpg",
      rating: 4.3,
      category: "Classic Literature & Fiction",
      price: 12,
      stock: 20,
      publisher: "Planeta",
      maturityRating: "Recommended for all audiences",
      description: `The Prisoner of heaven returns to the world of the Cemetery of Forgotten Books and the Sempere & Sons bookshop. It begins just before Christmas in Barcelona in 1957, one year after Daniel and Bea from THE SHADOW OF THE WIND have married. They now have a son, Julian, and are living with Daniel's father at Sempere & Sons. Fermin still works with them and is busy preparing for his wedding to Bernarda in the New Year. However something appears to be bothering him. Daniel is alone in the shop one morning when a mysterious figure with a pronounced limp enters. He spots one of their most precious volumes that is kept locked in a glass cabinet, a beautiful and unique illustrated edition of THE COUNT OF MONTE CRISTO. Despite the fact that the stranger seems to care little for books, he wants to buy this expensive edition. Then, to Daniel's surprise, the man inscribes the book with the words 'To Fermin Romero de Torres, who came back from the dead and who holds the key to the future'. This visit leads back to a story of imprisonment, betrayal and the return of a deadly rival ...`,
    },
    {
      title: "The Silmarillion",
      author: "J.R.R. Tolkien",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0075/9780007523221.jpg",
      rating: 4.8,
      category: "Fantasy",
      price: 9,
      stock: 12,
      publisher: "HarperCollins Publishers",
      maturityRating: "Recommended for all audiences",
      description: `The Silmarillion is an account of the Elder Days, of the First Age of Tolkien's world. It is the ancient drama to which the characters in The Lord of the Rings look back, and in whose events some of them such as Elrond and Galadriel took part. The tales of The Silmarillion are set in an age when Morgoth, the first Dark Lord, dwelt in Middle-Earth, and the High Elves made war upon him for the recovery of the Silmarils, the jewels containing the pure light of Valinor. This pivotal work features the revised, corrected text and includes, by way of an introduction, a fascinating letter written by Tolkien in 1951 in which he gives a full explanation of how he conceived the early Ages of Middle-earth.`,
    },
    {
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/2611/9780261103344.jpg",
      rating: 4.4,
      category: "Fantasy",
      price: 9,
      stock: 12,
      publisher: "HarperCollins Publishers",
      maturityRating: "NOT_MATURE",
      description: `Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely travelling further than the pantry of his hobbit-hole in Bag End. But his contentment is disturbed when the wizard, Gandalf, and a company of thirteen dwarves arrive on his doorstep one day to whisk him away on an unexpected journey 'there and back again'. They have a plot to raid the treasure hoard of Smaug the Magnificent, a large and very dangerous dragon... The prelude to The Lord of the Rings, The Hobbit has sold many millions of copies since its publication in 1937, establishing itself as one of the most beloved and influential books of the twentieth century.`,
    },
    {
      title: "The Lord of the Rings, The Fellowship of the Ring",
      author: "J.R.R. Tolkien",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/2611/9780261103573.jpg",
      rating: 4.8,
      category: "Fantasy",
      price: 12,
      stock: 20,
      publisher: "HarperCollins Publishers",
      maturityRating: "Recommended for all audiences",
      description: `Continuing the story begun in The Hobbit, this is the first part of Tolkien's epic masterpiece, The Lord of the Rings, featuring a striking black cover based on Tolkien's own design, the definitive text, and a detailed map of Middle-earth. Sauron, the Dark Lord, has gathered to him all the Rings of Power - the means by which he intends to rule Middle-earth. All he lacks in his plans for dominion is the One Ring - the ring that rules them all - which has fallen into the hands of the hobbit, Bilbo Baggins. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.`,
    },
    {
      title: "The Lord of the Rings, The Two Towers",
      author: "J.R.R. Tolkien",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/2611/9780261103580.jpg",
      rating: 4.8,
      category: "Fantasy",
      price: 12,
      stock: 18,
      publisher: "HarperCollins Publishers",
      maturityRating: "Recommended for all audiences",
      description: `The Two Towers is the second part of JRR Tolkien's epic masterpiece The Lord of the Rings. Frodo and the Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in the battle with an evil spirit in the Mines of Moria; and at the Falls of Rauros, Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape the rest of the company were attacked by Orcs. Now they continue their journey alone down the great River Anduin - alone, that is, save for the mysterious creeping figure that follows wherever they go.`,
    },
    {
      title: "The Lord of the Rings, The Return of the king",
      author: "J.R.R. Tolkien",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/2611/9780261103597.jpg",
      rating: 4.9,
      category: "Classic Literature & Fiction",
      price: 12,
      stock: 20,
      publisher: "HarperCollins Publishers",
      maturityRating: "Recommended for all audiences",
      description: `Concluding the story begun in The Hobbit, this is the final part of Tolkien's epic masterpiece, The Lord of the Rings. Featuring a striking black cover based on Tolkien's own design, the definitive text, and a detailed map of Middle-earth. The armies of the Dark Lord are massing as his evil shadow spreads ever wider. Men, Dwarves, Elves and Ents unite forces to do battle agains the Dark. Meanwhile, Frodo and Sam struggle further into Mordor in their heroic quest to destroy the One Ring.`,
    },
    {
      title: "Norwegian Wood",
      author: "Haruki Murakami",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0994/9780099448822.jpg",
      rating: 4.9,
      category: "Classic Literature & Fiction",
      price: 12,
      stock: 20,
      publisher: "Vintage Publishing",
      maturityRating: "Recommended for all audiences",
      description: `When he hears her favourite Beatles song, Toru Watanabe recalls his first love Naoko, the girlfriend of his best friend Kizuki. Immediately he is transported back almost twenty years to his student days in Tokyo, adrift in a world of uneasy friendships, casual sex, passion, loss and desire - to a time when an impetuous young woman called Midori marches into his life and he has to choose between the future and the past.`,
    },
    {
      title: "The Call of the Wild",
      author: "Jack London",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/1413/9780141321059.jpg",
      rating: 4.7,
      category: "Classic Literature & Fiction",
      price: 12,
      stock: 20,
      publisher: "Penguin Random House",
      maturityRating: "Recommended for all audiences",
      description:
        "Life is good for Buck in Santa Clara Valley, where he spends his days eating and sleeping in the golden sunshine. But one day a treacherous act of betrayal leads to his kidnap, and he is forced into a life of toil and danger. Dragged away to be a sledge dog in the harsh and freezing cold Yukon, Buck must fight for his survivial. Can he rise above his enemies and become the master of his realm once again?",
    },
    {
      title: "White Fang",
      author: "Jack London",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/1413/9780141321110.jpg",
      rating: 4.8,
      category: "Classic Literature & Fiction",
      price: 10,
      stock: 20,
      publisher: "Penguin Random House",
      maturityRating: "Recommended for all audiences",
      description:
        "Born in the wilds of the freezing cold Yukon, White Fang - half-dog, half-wolf - is the only animal in the litter to survive. He soon learns the harsh laws of nature, yet buried deep inside him are the distant memories of affection and love. Will this fiercely independent creature of the wild learn to trust man again? ",
    },
    {
      title: "The Complete MAUS",
      author: "Art Spiegelman",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/1410/9780141014081.jpg",
      rating: 4.8,
      category: "Comics & Graphic Novels",
      price: 13,
      stock: 15,
      publisher: "Penguin Books Ltd ",
      maturityRating: "Recommended for all audiences",
      description: `The Pulitzer Prize-winning Maus tells the story of Vladek Spiegelman, a Jewish survivor of Hitler's Europe, and his son, a cartoonist coming to terms with his father's story. Maus approaches the unspeakable through the diminutive. Its form, the cartoon (the Nazis are cats, the Jews mice), shocks us out of any lingering sense of familiarity and succeeds in 'drawing us closer to the bleak heart of the Holocaust' (The New York Times). Maus is a haunting tale within a tale. Vladek's harrowing story of survival is woven into the author's account of his tortured relationship with his aging father. Against the backdrop of guilt brought by survival, they stage a normal life of small arguments and unhappy visits. This astonishing retelling of our century's grisliest news is a story of survival, not only of Vladek but of the children who survive even the survivors. Maus studies the bloody pawprints of history and tracks its meaning for all of us.`,
    },
    {
      title: "For Whom The Bell Tolls",
      author: "Ernest Hemingway",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0992/9780099289821.jpg",
      rating: 4.4,
      category: "Classic Literature & Fiction",
      price: 12,
      stock: 20,
      publisher: "Vintage Publishing ",
      maturityRating: "Recommended for all audiences",
      description:
        "High in the pine forests of the Spanish Sierra, a guerrilla band prepares to blow up a vital bridge. Robert Jordan, a young American volunteer, has been sent to handle the dynamiting. There, in the mountains, he finds the dangers and the intense comradeship of war. And there he discovers Maria, a young woman who has escaped from Franco's rebels...",
    },
    {
      title: "James and the Giant Peach",
      author: "Roald Dahl",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/1413/9780141365459.jpg",
      rating: 4.3,
      category: "Kids",
      price: 12,
      stock: 20,
      publisher: "Penguin Random House Children",
      maturityRating: "NOT_MATURE",
      description: `For Mr and Mrs Trotter and their son James, life is pretty marvellous. Until, that is, Mr and Mrs Trotter are eaten by an angry rhinoceros. Poor Mr and Mrs Trotter you might say, but really you should say poor James. For when his parents die, he’s left to the care of his miserable, selfish, cruel aunts in a falling-down house on a hill in the south of England and for a while it looks as though that’s just where he’ll stay. Then, one day, James meets a strange old man who gives him a bag full of magical crystals and James’ life takes a most extraordinary turn. For when the magical crystals come into contact with a withered old peach tree, it starts to grow an enormous peach, bigger than anyone has ever seen, as big as a house, big enough to roll away all by itself and most certainly big enough for a small boy to crawl inside. Which is exactly what James decides to do.`,
    },
    {
      title: "Charlie and the Chocolate Factory",
      author: "Roald Dahl",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/1413/9780141365374.jpg",
      rating: 4.3,
      category: "Kids",
      price: 12,
      stock: 20,
      publisher: "Penguin Random House Children",
      maturityRating: "NOT_MATURE",
      description: `Welcome, my little friends! Welcome to the factory! ” For Charlie Bucket, life isn’t very easy. He and his mother and father live in a very small house with Charlie’s four grandparents who all share one bed between them.There isn ’ t much to eat besides cabbage soup and not even very much of that.What Charlie really longs for, is chocolate and not just any chocolate but Willy Wonka ’ s chocolate, made in the chocolate factory Charlie can almost see from his house.Mr Wonka is a mystery, a conundrum,one day he was there and the next day he suddenly vanished and nobody has been into his factory or cast eyes upon him ever since. Now Mr Wonka has offered five lucky children the chance to step inside the factory, five Golden Tickets hidden inside five bars of chocolate.All Charlie needs is one tiny, near - impossible stroke of luck.`,
    },
    {
      title: "Matilda",
      author: "Roald Dahl",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/1413/9780141369365.jpg",
      rating: 4.3,
      category: "Kids",
      price: 12,
      stock: 20,
      publisher: "Penguin Random House Children",
      maturityRating: "NOT_MATURE",
      description: `Matilda Wormwood 's father thinks she' s a little scab.Matilda 's mother spends all afternoon playing bingo. And Matilda' s headmistress Miss Trunchbull ? Well, she 's the worst of all. She is a big bully, who thinks all her pupils are rotten and locks them in the dreaded Chokey. As for Matilda, she' s an extraordinary little girl with a magical mind - and now she 's had enough. So all these grown-ups had better watch out, because Matilda is going to teach them a lesson they' ll never forget.`,
    },
    {
      title: "Winnie and Wilbur: Winnie the Witch",
      author: "Valerie Thomas",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/1927/9780192749055.jpg",
      rating: 4.3,
      category: "Kids",
      price: 12,
      stock: 20,
      publisher: "Oxford University Press",
      maturityRating: "NOT_MATURE",
      description: `Winnie shares her big black house with Wilbur her big black cat.So sometimes she accidentally trips over him.Ouch ! After some spells that make Wilbur look very silly, Winnie finds just the right magic to make sure she can always see him.It 's a colourful Winnie and Wilbur adventure! Korky Paul' s intricate artwork is full of madcap humour and crazy details to pore over.This edition features an accompanying audio CD with the story and magical music and sound effects.The spellbinding new look of this bestselling series celebrates the wonderful relationship that exists between Winnie the Witch and her big black cat, Wilbur.`,
    },
    {
      title: "What We 'll Build: Plans for Our Together Future",
      author: "Oliver Jeffers",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0083/9780008382209.jpg",
      rating: 4.2,
      category: "Kids",
      price: 10,
      stock: 18,
      publisher: "HarperCollins Publishers",
      maturityRating: "NOT_MATURE",
      description: `What shall we build, you and I? I' ll build your future and you 'll build mine. We' ll build a watch to keep our time. A father and daughter set about laying the foundations for their life together.Using their own special tools, they get to work; building memories to cherish, a home to keep them safe and love to keep them warm. From renowned, internationally bestselling picture - book creator and visual artist, Oliver Jeffers, comes this rare and enduring story about a parent 's boundless love, life' s endless opportunities and all we need to build a together future.`,
    },
    {
      title: "How to Catch a Star",
      author: "Oliver Jeffers",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0071/9780007150342.jpg",
      rating: 4.3,
      category: "Kids",
      price: 9,
      stock: 15,
      publisher: "HarperCollins Publishers",
      maturityRating: "NOT_MATURE",
      description: `An inspirational story of a boy who loved the stars so much, he decided to catch one of his very own.The beautifully illustrated, original debut picture book from shining talent Oliver Jeffers.There once was a boy who loved stars so much that he wished he had one of his very own. Every night he watched the stars in the sky from his bedroom window and dreamed of how he could be their friend and how they could play hide - and - go - seek together. So, one day, he decided to set about catching a star of his very own...`,
    },
    {
      title: "Faceless Killers: Kurt Wallander",
      author: "Henning Mankell",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0995/9780099571827.jpg",
      rating: 4.3,
      category: "Crime, Thriller, Mystery",
      price: 12,
      stock: 20,
      publisher: "Vintage Publishing",
      maturityRating: "Recommended for all audiences",
      description: `One frozen January morning at 5am, Inspector Wallander responds to what he believes is a routine call out. When he reaches the isolated farmhouse he discovers a bloodbath.An old man has been tortured and beaten to death, his wife lies barely alive beside his shattered body, both victims of a violence beyond reason.The woman supplies Wallander with his only clue: the perpetrators may have been foreign. When this is leaked to the press, it unleashes a tide of racism.Wallander 's life is a shambles. His wife has left him, his daughter refuses to speak to him, and even his ageing father barely tolerates him. He works tirelessly, eats badly, and drinks his nights away. But now Wallander must forget his troubles and throw himself into a battle against time and against mounting racial hatred.`,
    },
    {
      title: "The Hound of the Baskervilles",
      author: "Arthur Conan Doyle",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/1411/9780141199177.jpg",
      rating: 4.6,
      category: "Crime, Thriller, Mystery",
      price: 12,
      stock: 20,
      publisher: "Penguin Books Ltd ",
      maturityRating: "Recommended for all audiences",
      description: `Mr Holmes, they were the footprints of a gigantic hound!" The terrible spectacle of the beast, the fog of the moor, the discovery of a body: this classic horror story pits detective against dog, rationalism against the supernatural, good against evil. When Sir Charles Baskerville is found dead on the wild Devon moorland with the footprints of a giant hound nearby, the blame is placed on a family curse. It is left to Sherlock Holmes and Doctor Watson to solve the mystery of the legend of the phantom hound before Sir Charles' heir comes to an equally gruesome
  end.The Hound of the Baskervilles gripped readers when it was first serialised and has continued to hold its place in the popular imagination.`,
    },
    {
      title: "The Complete Sherlock Holmes",
      author: "Arthur Conan Doyle",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0995/9780099529934.jpg",
      rating: 4.8,
      category: "Crime, thriller, mystery",
      price: 18,
      stock: 21,
      publisher: "Penguin Books Ltd",
      maturityRating: "Recommended for all audiences",
      description: `This book contains all the investigations and adventures of the world 's most popular detective, Sherlock Holmes. From ' The Adventure of the Gloria Scott ' to ' His Last Bow ' we follow the illustrious career of this quintessential British hero from his university days to his final case. His efforts to uncover the truth take him all over the world and into conflict with all manner of devious criminals and dangerous villains, but thankfully his legendary powers of deduction, and his faithful companion Dr Watson, are more than up to the challenge.`,
    },
    {
      title: "Alice' s Adventures in Wonderland and Through the Looking Glass",
      author: "Lewis Carroll",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/1411/9780141199689.jpg",
      rating: 4.3,
      category: "Kids",
      price: 12,
      stock: 20,
      publisher: "Penguin Books Ltd",
      maturityRating: " NOT_MATURE ",
      description: `Alice ’ s collected adventures in the blazingly surreal Wonderland constitute nothing less than the beginning of modern fiction for children.Populated by a cast of unforgettable characters from the White Rabbit to the Queen of Hearts, as well as an addictive internal logic all their own, Carroll ’ s remarkable works fizz with imagination and invention.'Curiouser and curiouser!" cried Alice (she was so surprised, that for the moment she quite forgot how to speak good English). "Now I' m opening out like the largest telescope that ever was ! Goodbye, feet !`,
    },
  
    {
      title: "The Neverending Story",
      author: "Michael Ende",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/1400/9780140074314.jpg",
      rating: 4.7,
      category: "Kids",
      price: 10,
      stock: 20,
      publisher: "Penguin Books Ltd",
      maturityRating: "NOT_MATURE",
      description: `Unicorns, dragons, sprites, will-o' - the - wisps: the inhabitants of an enchanted world. And into this world - through the pages of an old book - ventures Bastian, a lonely boy of ten or twelve.But Fantastica is slowly decaying, its Childlike Empress dying.Only a real human being can set things right by giving the Empress a new name.Bastian takes up the challenge, and finds himself crossing the Swamps of Sadness and the Silver Mountains, meeting sorcerers and giants, bats and night - hobs, gnomes and racing snails, as he journeys bravely toward the Ivory Tower, Bastian 's quest is filled with all the wonders of myth and fairy tale. It is a fantasy adventure that will capture your heart - and recapture the magical dreams of childhood.`,
    },
    {
      title: "Momo",
      author: "Michael Ende",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/1403/9780140317534.jpg",
      rating: 4.3,
      category: "Kids",
      price: 12,
      stock: 20,
      publisher: "Penguin Books Ltd",
      maturityRating: "NOT_MATURE",
      description: `At the edge of the city, in the ruins of an old amphitheatre, there lives a little homelss girl called Momo. Momo has a special talent which she uses to help all her friends who come to visit her. Then one day the sinister men in grey arrive and silently take over the city. Only Momo has the power to resist them, and with the help of Professor Hora and his strange tortoise, Cassiopeia, she travels beyond the boundaries of time to uncover their dark secrets.`,
    },
    {
      title: "A Game of Thrones - A Song of Ice and Fire Book 1",
      author: "George R.R. Martin",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0074/9780007448036.jpg",
      rating: 4.6,
      category: "Fantasy",
      price: 17,
      stock: 20,
      publisher: "HarperCollins Publishers",
      maturityRating: "MATURE",
      description: `The first volume in the A Song of Ice and Fire series – unquestionably one of the greatest fantasy epics of all time. Here, we are introduced to the Seven Kingdoms of Westeros, and the major players with eyes on its Iron Throne. As noble families battle for power, greater threats face them all: for winter is coming to Westeros, and here, winter can last a lifetime. Summers span decades. Winter can last a lifetime. And the struggle for the Iron Throne has begun. As Warden of the north, Lord Eddard Stark counts it a curse when King Robert bestows on him the office of the Hand. His honour weighs him down at court where a true man does what he will, not what he must ... and a dead enemy is a thing of beauty. The old gods have no power in the south, Stark' s family is split and there is treachery at court.Worse, the vengeance - mad heir of the deposed Dragon King has grown to maturity in exile in the Free Cities.He claims the Iron Throne.`,
    },
    {
      title: "A Clash of Kings - A Song of Ice and Fire Book 2",
      author: "George R.R.Martin",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0074/9780007447831.jpg",
      rating: 4.7,
      category: "Fantasy",
      price: 12,
      stock: 20,
      publisher: "HarperCollins Publishers",
      maturityRating: "MATURE",
      description: `Throughout Westeros, the cold winds are rising. From the ancient citadel of Dragonstone to the forbidding lands of Winterfell, chaos reigns as pretenders to the Iron Throne of the Seven Kingdoms stake their claims through tempest, turmoil and war. As a prophecy of doom cuts across the sky - a comet the colour of blood and flame - five factions struggle for control of a divided land.Brother plots against brother and the dead rise to walk in the night.Against a backdrop of incest, fratricide, alchemy and murder, the price of glory is measured in blood.`,
    },
    {
      title:
        "A Storm of Swords: Part 1 Steel and Snow - A Song of Ice and Fire Book 3",
      author: "George R.R.Martin",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0074/9780007447848.jpg",
      rating: 4.3,
      category: "Fantasy",
      price: 12,
      stock: 20,
      publisher: "HarperCollins Publishers",
      maturityRating: "MATURE",
      description: `Winter approaches Westeros like an angry beast.The Seven Kingdoms are divided by revolt and blood feud.In the northern wastes, a horde of hungry, savage people steeped in the dark magic of the wilderness is poised to invade the Kingdom of the North where Robb Stark wears his new - forged crown. And Robb 's defences are ranged against the South, the land of the cunning and cruel Lannisters, who have his younger sisters in their power. Throughout Westeros, the war for the Iron Throne rages more fiercely than ever, but if the Wall is breached, no king will live to claim it.`,
    },
    {
      title:
        "A Storm of Swords: Part 2 Blood and Gold (Reissue) - A Song of Ice and Fire Book 3",
      author: "George R.R. Martin",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0074/9780007447855.jpg",
      rating: 4.3,
      category: "Fantasy",
      price: 16,
      stock: 20,
      publisher: "HarperCollins Publishers",
      maturityRating: "MATURE",
      description: `The Starks are scattered. Robb Stark may be King in the North, but he must bend to the will of the old tyrant Walder Frey if he is to hold his crown. And while his youngest sister, Arya, has escaped the clutches of the depraved Cersei Lannister and her son, the capricious boy-king Joffrey, Sansa Stark remains their captive. Meanwhile, across the ocean, Daenerys Stormborn, the last heir of the Dragon King, delivers death to the slave-trading cities of Astapor and Yunkai as she approaches Westeros with vengeance in her heart.`,
    },
    {
      title: "A Feast for Crows - A Song of Ice and Fire Book 4",
      author: "George R.R. Martin",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0074/9780007447862.jpg",
      rating: 4.3,
      category: "Fantasy",
      price: 16,
      stock: 20,
      publisher: "HarperCollins Publishers",
      maturityRating: "MATURE",
      description: `The Lannisters are in power on the Iron Throne. The war in the Seven Kingdoms has burned itself out, but in its bitter aftermath new conflicts spark to life. The Martells of Dorne and the Starks of Winterfell seek vengeance for their dead. Euron Crow' s Eye, as black a pirate as ever raised a sail, returns from the smoking ruins of Valyria to claim the Iron Isles. From the icy north, where Others threaten the Wall, apprentice Maester Samwell Tarly brings a mysterious babe in arms to the Citadel.As plots, intrigue and battle threaten to engulf Westeros, victory will go to the men and women possessed of the coldest steel and the coldest hearts.`,
    },
  
    {
      title:
        "A Dance With Dragons: Part 1 Dreams and Dust - A Song of Ice and Fire Book 5",
      author: "George R.R. Martin",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0074/9780007466078.jpg",
      rating: 4.3,
      category: "Fantasy",
      price: 16,
      stock: 20,
      publisher: "HarperCollins Publishers",
      maturityRating: "MATURE",
      description: `In the aftermath of a colossal battle, new threats are emerging from every direction.Tyrion Lannister, having killed his father, and wrongfully accused of killing his nephew, King Joffrey, has escaped from King 's Landing with a price on his head. To the north lies the great Wall of ice and stone - a structure only as strong as those guarding it. Eddard Stark' s bastard son Jon Snow has been elected 998th Lord Commander of the Night 's Watch. But Jon has enemies both inside and beyond the Wall. And in the east Daenerys Targaryen struggles to hold a city built on dreams and dust`,
    },
    {
      title:
        "A Dance With Dragons: Part 2 After the Feast - A Song of Ice and Fire Book 5 ",
      author: "George R.R. Martin",
      img: "https://cdn.waterstones.com/bookjackets/large/9780/0074/9780007466078.jpg",
      rating: 4.8,
      category: "Fantasy",
      price: 16,
      stock: 20,
      publisher: "HarperCollins Publishers ",
      maturityRating: "MATURE",
      description: `The future of the Seven Kingdoms hangs in the balance. In King' s Landing the Queen Regent, Cersei Lannister, awaits trial, abandoned by all those she trusted; while in the eastern city of Yunkai her brother Tyrion has been sold as a slave. From the Wall, having left his wife and the Red Priestess Melisandre under the protection of Jon Snow, Stannis Baratheon marches south to confront the Boltons at Winterfell.But beyond the Wall the wildling armies are massing for an assault...On all sides bitter conflicts are reigniting, played out by a grand cast of outlaws and priests, soldiers and skinchangers, nobles and slaves.The tides of destiny will inevitably lead to the greatest dance of all.`,
    },
  ];

  const seedAdmin = [
    {
      name: "Martin",
      lastname: "Elmascapo",
      address: "calle falsa 123",
      username: "martinlibrolover",
      email: "martin@martin.com",
      password: "Hola123123",
      isAdmin: true
    },
    {
      name: "Juan Domingo",
      lastname: "Perón",
      address: "San Vicente 123",
      username: "juan_domingo",
      email: "el_primer_trabajador@mail.com",
      password: "Hola123123",
    },
    {
      name: "Diego Armando",
      lastname: "Maradona",
      address: "Bella Vista 123",
      username: "diegote",
      email: "el_diego@mail.com",
      password: "Hola123123",
    },
    {
      name: "Britney",
      lastname: "Spears",
      address: "EEUU 123",
      username: "freeBritney",
      email: "britney@mail.com",
      password: "Hola123123",
    },
    {
      name: "Señor",
      lastname: "Analfabeto",
      address: "Muy lejos 123",
      username: "NoSabeLeer",
      email: "queseyo@mail.com",
      password: "Hola123123",
    },
  
  ]

  const seedRatings = [
    {
      value: 4,
      bookId: 1,
      userId: 1,
    },
    {
      value: 5,
      bookId: 1,
      userId: 2,
    },
    {
      value: 3,
      bookId: 1,
      userId: 3,
    },
    {
      value: 1,
      bookId: 1,
      userId: 4,
    },
  ]
  
  module.exports = {seedBooks, seedAdmin, seedRatings};